### ISSUE TITLE
Abysmal performance of configurable AI-task null checks

### ISSUE THREAD

**Issue by Tommsy64** [Laike-Endaril/Dynamic-Stealth#101]
Commit cc36f9e leaves me nonplussed.

`replaceNPEAttackTargetTasks(EntityLiving)` is called *every single tick* for *every single  entity*.  `replaceNPEAttackTargetTasks(EntityLiving)` duplicates the entire `taskEntries` LinkedHashSet into a freshly allocated array. This copy is then iterated, calling `badNullTargetHandling(EntityAIBase)` for each element. All of this is happens *again* for another `EntityAITasks` object.

This isn't too big of a problem; however, the worst of it is in `badNullTargetHandling(EntityAIBase)`, which runs a [customized](https://github.com/Laike-Endaril/Fantastic-Lib/blob/1.12.2/src/main/java/com/fantasticsource/tools/Tools.java#L280-L287) (not sure why) regex split on a config string, allocating many String objects. Recall that this happens **every single tick** for just about **every single entity**, **TWICE**.

A test modded server with a single player and ~50 `EntityLiving`'s was crawling at ~10 TPS.

**Comment by Laike-Endaril** [comment]
(See further conversation in the related PR post: https://github.com/Laike-Endaril/Dynamic-Stealth/pull/102)

**Comment by Laike-Endaril** [comment]
This should be fixed in the latest release (104)
