### ISSUE TITLE
Aether Legacy not working with Dynamic Stealth

### ISSUE THREAD

**Issue by Heaveness** [Laike-Endaril/Dynamic-Stealth#104]
I've been working on this spin-off mod-pack for a long while now. I've noticed there is a compatibility issue with Aether Legacy's boss mobs such as Sun Spirit and Slider. I put both of them in the Entity Specific Full Bypass but it doesn't effect them at all. The Bosses have this problem where they do nothing when you attack them. Sliders keep resetting back to sleeping when hit with its pickaxe and Sun Spirits do absolutely nothing. When I remove Dynamic Stealth, they go back to normal. Anyway to fix this?

**Comment by Laike-Endaril** [comment]
I'm not familiar enough with Aether to say for sure, but you may want to check whether they're multi-part entities, and if so, to add all parts to the full bypass.

I'll take a look and see if the full bypass isn't bypassing something as well.

If you're not already doing so, use the flib reference files to search for entity names (found in config/fantasticlib/reference after running the pack)

**Comment by Laike-Endaril** [comment]
I have found some possible causes in the code, and am working on them, but I still suggest doing the above as well if you haven't.

**Comment by Laike-Endaril** [comment]
The new release (104) should cover this, so long as you have all the right entities in the full bypass, but I'll leave it open for now.  Tell me how it goes if you get a chance to try it.

**Comment by Heaveness** [comment]
Oh thank you very much! I will do some thorough testing and you came at a perfect time too. I've been working on updating my mod-pack and the new update is very close to finishing, so this dropping by is just wonderful! It's unfortunately very late here when I just read this message. I will give it a try tomorrow morning.  :)

**Comment by Heaveness** [comment]
[crash-2020-08-16_22.18.42-server.txt](https://github.com/Laike-Endaril/Dynamic-Stealth/files/5081837/crash-2020-08-16_22.18.42-server.txt)

Just had this crash when I tried to fly around the Aether. I was looking for a Slider at the time then random crash. Also getting constant Main Menu crash with Armor Stand Configurator after the first crash happens. I didn't change anything from the new config. All I did was update the new one with similar settings as the old one.

Nevermind, I can't even make a new save anymore... It just crashes non-stop. Same exact crash-report

**Comment by Laike-Endaril** [comment]
The latest crash was due to a new error in version 1.12.2.104.  The new error should be fixed in latest release (105).

**Comment by Heaveness** [comment]
I just checked both bosses and flew around. The new update fixed it! Thank you so much for fixing it! You are a wonderful person. I was going to resort to moving to Aether 2 which would have given me a huge amount of work and headache to integrate, but you saved a long headache in the long run. Once again thank you.
