### ISSUE TITLE
Crash when summoning customnpc

### ISSUE THREAD

**Issue by ghost** [Laike-Endaril/Dynamic-Stealth#106]
Crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.10.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  BlockbusterCore (blockbuster-1.6.6-1.12.2.jar)
  McLib core mod (mclib-1.0.4-1.12.2.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 8/8/20 4:21 PM
Description: Rendering entity in world

java.lang.NoSuchFieldError: WHITE
	at com.fantasticsource.dynamicstealth.client.HUD.drawOPHUD(HUD.java:368)
	at com.fantasticsource.dynamicstealth.client.HUD.entityRender(HUD.java:150)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_89_HUD_entityRender_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:203)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:16)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.fantasticsource.dynamicstealth.client.HUD.drawOPHUD(HUD.java:368)
	at com.fantasticsource.dynamicstealth.client.HUD.entityRender(HUD.java:150)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_89_HUD_entityRender_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:203)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:16)

-- Entity being rendered --
Details:
	Entity Type: minecraft:sheep (net.minecraft.entity.passive.EntitySheep)
	Entity ID: 168
	Entity Name: Sheep
	Entity's Exact location: 190.28, 70.00, 317.48
	Entity's Block location: World: (190,70,317), Chunk: (at 14,4,13 in 11,19; contains blocks 176,0,304 to 191,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderSheep@26725485
	Location: 24.10,-4.10,33.40 - World: (24,-5,33), Chunk: (at 8,-1,1 in 1,2; contains blocks 16,0,32 to 31,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -87.1875
	Delta: 0.81999356
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['rtyuzer'/83, l='MpServer', x=166.23, y=74.11, z=284.20]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (24,64,248), Chunk: (at 8,4,8 in 1,15; contains blocks 16,0,240 to 31,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6043052 game time, 1154024 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 62 total; [EntityPainting['Painting'/71, l='MpServer', x=100.50, y=88.00, z=98.03], EntityPainting['Painting'/73, l='MpServer', x=100.50, y=82.00, z=103.03], EntityPainting['Painting'/70, l='MpServer', x=102.50, y=88.00, z=100.03], EntityPainting['Painting'/54, l='MpServer', x=91.50, y=88.00, z=89.03], EntityPainting['Painting'/53, l='MpServer', x=93.50, y=88.00, z=91.03], EntityPainting['Painting'/55, l='MpServer', x=89.03, y=88.00, z=91.50], EntityPainting['Painting'/56, l='MpServer', x=87.50, y=88.00, z=93.03], EntityPainting['Painting'/57, l='MpServer', x=86.03, y=88.00, z=94.50], EntityPainting['Painting'/68, l='MpServer', x=97.50, y=88.00, z=95.03], EntityPainting['Painting'/69, l='MpServer', x=96.50, y=88.00, z=94.03], EntityPainting['Painting'/63, l='MpServer', x=90.50, y=82.00, z=96.03], EntityPainting['Painting'/58, l='MpServer', x=84.03, y=88.00, z=96.50], EntityPainting['Painting'/62, l='MpServer', x=94.50, y=81.00, z=97.03], EntityPainting['Painting'/72, l='MpServer', x=99.50, y=88.00, z=97.03], EntityPainting['Painting'/61, l='MpServer', x=95.50, y=81.00, z=98.03], EntityPainting['Painting'/64, l='MpServer', x=88.50, y=81.00, z=98.03], EntityPainting['Painting'/71, l='MpServer', x=100.50, y=88.00, z=98.03], EntityPainting['Painting'/59, l='MpServer', x=82.03, y=88.00, z=98.50], EntityPainting['Painting'/60, l='MpServer', x=81.03, y=88.00, z=99.50], EntityPainting['Painting'/65, l='MpServer', x=87.03, y=82.00, z=99.50], EntityPainting['Painting'/70, l='MpServer', x=102.50, y=88.00, z=100.03], EntityPainting['Painting'/76, l='MpServer', x=97.50, y=81.00, z=100.03], EntityPainting['Painting'/66, l='MpServer', x=86.03, y=82.00, z=100.50], EntityPainting['Painting'/75, l='MpServer', x=98.50, y=80.50, z=101.03], EntityPainting['Painting'/42, l='MpServer', x=79.03, y=88.00, z=101.50], EntityPainting['Painting'/67, l='MpServer', x=84.03, y=81.00, z=102.50], EntityPainting['Painting'/74, l='MpServer', x=98.97, y=82.00, z=101.50], EntityPainting['Painting'/73, l='MpServer', x=100.50, y=82.00, z=103.03], EntitySheep['Sheep'/168, l='MpServer', x=190.28, y=70.00, z=317.48], EntityPlayerSP['rtyuzer'/83, l='MpServer', x=166.23, y=74.11, z=284.20], EntityPainting['Painting'/49, l='MpServer', x=69.03, y=88.00, z=111.50], EntityPainting['Painting'/48, l='MpServer', x=70.03, y=88.00, z=110.50], EntityPainting['Painting'/47, l='MpServer', x=72.03, y=88.00, z=108.50], EntityPainting['Painting'/46, l='MpServer', x=73.03, y=88.00, z=107.50], EntityPainting['Painting'/45, l='MpServer', x=74.03, y=88.00, z=106.50], EntityPainting['Painting'/43, l='MpServer', x=77.03, y=88.00, z=103.50], EntityPainting['Painting'/44, l='MpServer', x=76.03, y=88.00, z=104.50], EntityPainting['Painting'/52, l='MpServer', x=76.03, y=82.00, z=110.50], EntityPainting['Painting'/50, l='MpServer', x=78.03, y=82.00, z=108.50], EntityPainting['Painting'/51, l='MpServer', x=77.50, y=82.00, z=109.03], EntityPainting['Painting'/42, l='MpServer', x=79.03, y=88.00, z=101.50], EntityPainting['Painting'/60, l='MpServer', x=81.03, y=88.00, z=99.50], EntityPainting['Painting'/59, l='MpServer', x=82.03, y=88.00, z=98.50], EntityPainting['Painting'/58, l='MpServer', x=84.03, y=88.00, z=96.50], EntityPainting['Painting'/67, l='MpServer', x=84.03, y=81.00, z=102.50], EntityPainting['Painting'/57, l='MpServer', x=86.03, y=88.00, z=94.50], EntityPainting['Painting'/66, l='MpServer', x=86.03, y=82.00, z=100.50], EntityPainting['Painting'/56, l='MpServer', x=87.50, y=88.00, z=93.03], EntityPainting['Painting'/65, l='MpServer', x=87.03, y=82.00, z=99.50], EntityPainting['Painting'/64, l='MpServer', x=88.50, y=81.00, z=98.03], EntityPainting['Painting'/55, l='MpServer', x=89.03, y=88.00, z=91.50], EntityPainting['Painting'/63, l='MpServer', x=90.50, y=82.00, z=96.03], EntityPainting['Painting'/54, l='MpServer', x=91.50, y=88.00, z=89.03], EntityPainting['Painting'/53, l='MpServer', x=93.50, y=88.00, z=91.03], EntityPainting['Painting'/62, l='MpServer', x=94.50, y=81.00, z=97.03], EntityPainting['Painting'/61, l='MpServer', x=95.50, y=81.00, z=98.03], EntityPainting['Painting'/69, l='MpServer', x=96.50, y=88.00, z=94.03], EntityPainting['Painting'/68, l='MpServer', x=97.50, y=88.00, z=95.03], EntityPainting['Painting'/76, l='MpServer', x=97.50, y=81.00, z=100.03], EntityPainting['Painting'/72, l='MpServer', x=99.50, y=88.00, z=97.03], EntityPainting['Painting'/74, l='MpServer', x=98.97, y=82.00, z=101.50], EntityPainting['Painting'/75, l='MpServer', x=98.50, y=80.50, z=101.03]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 440929752 bytes (420 MB) / 1644167168 bytes (1568 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 43 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version               | Source                                            | Signature                                |
	|:------ |:------------------ |:--------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2                | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                | 9.42                  | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                | 8.0.99.99             | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge              | 14.23.5.2854          | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy  | 1.0.0                 | minecraft.jar                                     | None                                     |
	| LCHIJA | littletilescore    | 1.0.0                 | minecraft.jar                                     | None                                     |
	| LCHIJA | foamfixcore        | 7.7.4                 | minecraft.jar                                     | None                                     |
	| LCHIJA | opencomputers|core | 1.7.5.192             | minecraft.jar                                     | None                                     |
	| LCHIJA | mclib              | 1.0.4                 | mclib-1.0.4-1.12.2.jar                            | None                                     |
	| LCHIJA | aperture           | 1.3.6                 | aperture-1.3.6-1.12.2.jar                         | None                                     |
	| LCHIJA | armourers_workshop | 1.12.2-0.50.3         | Armourers-Workshop-1.12.2-0.50.3.jar              | None                                     |
	| LCHIJA | backstab           | 1.0.3.2               | backstab-1.12.2-1.0.3.2.jar                       | None                                     |
	| LCHIJA | bibliocraft        | 2.4.5                 | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| LCHIJA | metamorph          | 1.1.10                | metamorph-1.1.10-1.12.2.jar                       | None                                     |
	| LCHIJA | blockbuster        | 1.6.6                 | blockbuster-1.6.6-1.12.2.jar                      | None                                     |
	| LCHIJA | carryon            | 1.12.3                | carryon-1.12.2-1.12.3.15.jar                      | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHIJA | cctweaked          | 1.87.0                | cc-tweaked-1.12.2-1.87.0.jar                      | None                                     |
	| LCHIJA | computercraft      | 1.87.0                | cc-tweaked-1.12.2-1.87.0.jar                      | None                                     |
	| LCHIJA | cfm                | 6.3.0                 | cfm-6.3.0-mc1.12.2.jar                            | None                                     |
	| LCHIJA | chunkanimator      | 1.2                   | ChunkAnimator-MC1.12-1.2.jar                      | None                                     |
	| LCHIJA | enhancedvisuals    | 1.3.0                 | EnhancedVisuals_v1.3.15_mc1.12.2.jar              | None                                     |
	| LCHIJA | creativecore       | 1.10.0                | CreativeCore_v1.10.16_mc1.12.2.jar                | None                                     |
	| LCHIJA | custombackgrounds  | 1.0                   | CustomBackgrounds-MC1.12-1.1.1.jar                | None                                     |
	| LCHIJA | custommainmenu     | 2.0.9.1               | CustomMainMenu-MC1.12.2-2.0.9.1.jar               | None                                     |
	| LCHIJA | customnpcs         | 1.12                  | CustomNPCs_1.12.2-(01Oct19).jar                   | None                                     |
	| LCHIJA | fantasticlib       | 1.12.2.036            | FantasticLib-1.12.2.036.jar                       | None                                     |
	| LCHIJA | dynamicstealth     | 1.12.2.103            | DynamicStealth-1.12.2.103.jar                     | None                                     |
	| LCHIJA | firstaid           | 1.6.                  | firstaid-1.6.6.jar                                | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | flansmod           | 5.5.2                 | Flan's Mod-1.12.2-5.5.2.jar                       | None                                     |
	| LCHIJA | flansmodapocalypse | 1.0                   | Flan's Mod-1.12.2-5.5.2.jar                       | None                                     |
	| LCHIJA | foamfix            | 0.10.10-1.12.2        | foamfix-0.10.10-1.12.2.jar                        | None                                     |
	| LCHIJA | grapplemod         | 1.12.2-v11.1          | grapplemod-v11.1-1.12.2.jar                       | None                                     |
	| LCHIJA | lucraftcore        | 1.12.2-2.4.10         | LucraftCore-1.12.2-2.4.10.jar                     | None                                     |
	| LCHIJA | heroesexpansion    | 1.12.2-1.3.5          | HeroesExpansion-1.12.2-1.3.5.jar                  | None                                     |
	| LCHIJA | littletiles        | 1.5.0                 | LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar         | None                                     |
	| LCHIJA | malisiscore        | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                      | None                                     |
	| LCHIJA | malisisadvert      | 1.12.2-6.1.0          | malisisadvert-1.12.2-6.1.0.jar                    | None                                     |
	| LCHIJA | malisisdoors       | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| LCHIJA | opencomputers      | 1.7.5.192             | OpenComputers-MC1.12.2-1.7.5.192.jar              | None                                     |
	| LCHIJA | resourceloader     | 1.5.3                 | ResourceLoader-MC1.12.1-1.5.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | worldedit          | 6.1.10-SNAPSHOT       | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| UD     | blockbuster_core   | 1.6.6                 | minecraft.jar                                     | None                                     |
	| UD     | mclib_core         | 1.0.4                 | minecraft.jar                                     | None                                     |

	Loaded coremods (and transformers): 
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.10.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  
BlockbusterCore (blockbuster-1.6.6-1.12.2.jar)
  mchorse.blockbuster.core.BBCoreClassTransformer
McLib core mod (mclib-1.0.4-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13560 Compatibility Profile Context 26.20.11030.14002' Renderer: 'AMD Radeon(TM) Vega 8 Graphics'
	Armourer's Workshop: 
		Baking Queue: 0
		Request Queue: 0
		Texture Paint Type: TEXTURE_REPLACE
		Multipass Skin Rendering: true
	Render Layers:
		 Render Class: net.minecraft.client.renderer.entity.RenderSubPlayer
			moe.plushie.armourers_workshop.client.render.entity.ModelResetLayer
			net.minecraft.client.renderer.entity.layers.LayerBipedArmor
			net.minecraft.client.renderer.entity.layers.LayerArrow
			net.minecraft.client.renderer.entity.layers.LayerDeadmau5Head
			net.minecraft.client.renderer.entity.layers.LayerCape
			net.minecraft.client.renderer.entity.layers.LayerCustomHead
			net.minecraft.client.renderer.entity.layers.LayerElytra
			net.minecraft.client.renderer.entity.layers.LayerEntityOnShoulder
			lucraft.mods.lucraftcore.superpowers.render.SuperpowerRenderLayer
			lucraft.mods.lucraftcore.extendedinventory.render.LayerRendererExtendedInventory
			moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererHeldItem
			moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererPlayer
			lucraft.mods.heroesexpansion.client.render.layer.LayerRendererHighlightEntity
			lucraft.mods.heroesexpansion.client.render.layer.LayerRendererFrozen
			lucraft.mods.heroesexpansion.client.render.layer.LayerRendererForceField
			lucraft.mods.heroesexpansion.client.render.layer.LayerRendererWebbing
		 Render Class: net.minecraft.client.renderer.entity.RenderSubPlayer
			moe.plushie.armourers_workshop.client.render.entity.ModelResetLayer
			net.minecraft.client.renderer.entity.layers.LayerBipedArmor
			net.minecraft.client.renderer.entity.layers.LayerArrow
			net.minecraft.client.renderer.entity.layers.LayerDeadmau5Head
			net.minecraft.client.renderer.entity.layers.LayerCape
			net.minecraft.client.renderer.entity.layers.LayerCustomHead
			net.minecraft.client.renderer.entity.layers.LayerElytra
			net.minecraft.client.renderer.entity.layers.LayerEntityOnShoulder
			lucraft.mods.lucraftcore.superpowers.render.SuperpowerRenderLayer
			lucraft.mods.lucraftcore.extendedinventory.render.LayerRendererExtendedInventory
			moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererPlayer
			com.fantasticsource.mctools.aw.ForcedAWSkinOverrides$AWSkinRenderLayerWrapper
			lucraft.mods.heroesexpansion.client.render.layer.LayerRendererHighlightEntity
			lucraft.mods.heroesexpansion.client.render.layer.LayerRendererFrozen
			lucraft.mods.heroesexpansion.client.render.layer.LayerRendererForceField
			lucraft.mods.heroesexpansion.client.render.layer.LayerRendererWebbing
			lucraft.mods.lucraftcore.sizechanging.render.LayerSizeChanging
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.13560 Compatibility Profile Context 26.20.11030.14002, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx

**Comment by Laike-Endaril** [comment]
Has this happened multiple times, or only once?

**Comment by ghost** [comment]
multiple times

**Comment by Laike-Endaril** [comment]
This is a very odd one.  I'll probably reconstruct your modpack on my machine (at least the mods in it; won't worry about configs unless I need to), and see if I can reproduce the issue

**Comment by Laike-Endaril** [comment]
I believe this is fixed in the latest version of DS (106).  Give it a try and tell me if it fixes the crash when you get a chance.

**Comment by Laike-Endaril** [comment]
Closed for now; will reopen if you get the same crash on latest version
