### ISSUE TITLE
对Mowzie's Mobs的AI负优化

### ISSUE THREAD

**Issue by C-Zking** [Laike-Endaril/Dynamic-Stealth#108]
The AI of mowzie's mobs is doing very well, but when it's applied to them, things get really bad,。and they can't act accordingly，some of them will just use their skill without doing anything。

**Comment by Laike-Endaril** [comment]
I will try to do some testing with Mowzie's Mobs this weekend

**Comment by Laike-Endaril** [comment]
My testing shows that in general, Mowzie's Mobs does not work well with Dynamic Stealth, so I suggest this:

In (mod settings -> dynamic stealth -> server settings -> entity-specific full bypass)
Add these entries:

mowziesmobs:foliaath
mowziesmobs:baby_foliaath
mowziesmobs:ferrous_wroughtnaut
mowziesmobs:barakoan_barakoana
mowziesmobs:barakoana
mowziesmobs:barakoaya
mowziesmobs:barakoan_player
mowziesmobs:barako
mowziesmobs:frostmaw
mowziesmobs:grottol
mowziesmobs:lantern
mowziesmobs:naga
mowziesmobs:sunstrike
mowziesmobs:solar_beam
mowziesmobs:boulder
mowziesmobs:axe_attack
mowziesmobs:icebreath
mowziesmobs:ice_ball
mowziesmobs:frozen_controller
mowziesmobs:ring
mowziesmobs:dart
mowziesmobs:poison_ball
mowziesmobs:super_nova
mowziesmobs:block_swapper

This should allow all of Mowzie's Mobs to act as normal, without applying DS AI or most other DS systems to them.

Note: after running the game at least once, entity IDs can be found in the file (config -> fantasticlib -> reference -> entities.txt)

**Comment by C-Zking** [comment]
> 我的测试表明，总体而言，Mowzie的小怪不能与Dynamic Stealth配合使用，因此我建议这样做：
> 
> 在（mod设置->动态隐身->服务器设置->特定于实体的完全旁路）中，
> 添加以下条目：
> 
> mowziesmobs：foliaath
> mowziesmobs：baby_foliaath
> mowziesmobs：ferrous_wroughtnaut
> mowziesmobs：barakoan_barakoana
> mowziesmobs：barakoana
> mowziesmobs：barakoaya
> mowziesmobs：barakoan_player
> mowziesmobs：巴拉
> mowziesmobs：frostmaw
> mowziesmobs：grottol
> mowziesmobs：灯笼
> mowziesmobs：娜迦
> mowziesmobs：sunstrike
> mowziesmobs：solar_beam
> mowziesmobs：大石
> mowziesmobs：axe_attack
> mowziesmobs：冰
> 呼吸的小精灵
> 生物：冰球的
> 小精灵生物：冻结的控制器小精灵的生物：环小
> 精灵的生物：飞镖的
> 小精灵
> 生物：毒
> 球的小精灵生物：超级新星的小精灵生物：block_swapper
> 
> 这应该允许所有Mowzie的小怪都能正常工作，而无需对其应用DS AI或大多数其他DS系统。
> 
> 注意：至少运行一次游戏后，可以在文件中找到实体ID（配置-> fantasticlib->参考-> Entitys.txt）



> My testing shows that in general, Mowzie's Mobs does not work well with Dynamic Stealth, so I suggest this:
> 
> In (mod settings -> dynamic stealth -> server settings -> entity-specific full bypass)
> Add these entries:
> 
> mowziesmobs:foliaath
> mowziesmobs:baby_foliaath
> mowziesmobs:ferrous_wroughtnaut
> mowziesmobs:barakoan_barakoana
> mowziesmobs:barakoana
> mowziesmobs:barakoaya
> mowziesmobs:barakoan_player
> mowziesmobs:barako
> mowziesmobs:frostmaw
> mowziesmobs:grottol
> mowziesmobs:lantern
> mowziesmobs:naga
> mowziesmobs:sunstrike
> mowziesmobs:solar_beam
> mowziesmobs:boulder
> mowziesmobs:axe_attack
> mowziesmobs:icebreath
> mowziesmobs:ice_ball
> mowziesmobs:frozen_controller
> mowziesmobs:ring
> mowziesmobs:dart
> mowziesmobs:poison_ball
> mowziesmobs:super_nova
> mowziesmobs:block_swapper
> 
> This should allow all of Mowzie's Mobs to act as normal, without applying DS AI or most other DS systems to them.
> 
> Note: after runni the game at least once, entity IDs can be found in the file (config -> fantasticlib -> reference -> entities.txt)

**Comment by C-Zking** [comment]
thank you very much!
