### ISSUE TITLE
Crash Report - Deadly Monsters

### ISSUE THREAD

**Issue by Dune-Jumper** [Laike-Endaril/Dynamic-Stealth#110]
https://pastebin.com/48KgtVeE [Deadly Monsters](https://www.curseforge.com/minecraft/mc-mods/deadly-monsters)

**Comment by Laike-Endaril** [comment]
Your words are few but meaningful.  I appreciate that.

Open the DS mod config and go to
Server settings -> AI -> add null checks to AI

And add this entry:
dmonsters, com.dmonsters.ai.EntityAITopielecFollowPlayer

Then restart the server (or client if single player)

**Comment by Dune-Jumper** [comment]
Thank you!

**Comment by Laike-Endaril** [comment]
No problem
