### ISSUE TITLE
Having an Issue with Dynamic Stealth and Ancient Warfare 2 mob

### ISSUE THREAD

**Issue by Heaveness** [Laike-Endaril/Dynamic-Stealth#111]
Not exactly sure where to start with this issue. This seems to happen every-time a mob spawns or a particular mob spawning? I'm not sure. Maybe you can help me figure it out. I will post more information when I get them.

[crash-2020-09-28_17.35.41-client.txt](https://github.com/Laike-Endaril/Dynamic-Stealth/files/5295848/crash-2020-09-28_17.35.41-client.txt)

**Comment by Heaveness** [comment]
Hmmm I think it might have to do with the on-point threat and health bar? One of my guys told me he reverted back the changes made to Dynamic Stealth with the on-point HUD Health bar and he is no longer crashing.

**Comment by Laike-Endaril** [comment]
Try running with the latest version of Fantastic Lib (37) alongside the latest DS.  FLib 37 may fix this bug.

**Comment by Heaveness** [comment]
While I think the problem has been solved and I haven't noticed any significant crashes when spawning AW2. There is another problem that started to pop up and I am not sure if it's because of the new update or not. Mods like the Ping and StatusTags are now being blacked out when viewed at certain angles.

**Comment by Heaveness** [comment]
Another problem with mobs but this is regarding the issue with another mob with your mod. I am on the newest version.

[crash-2020-10-17_18.11.24-client.txt](https://github.com/Laike-Endaril/Dynamic-Stealth/files/5396414/crash-2020-10-17_18.11.24-client.txt)

**Comment by Heaveness** [comment]
Getting another crash from two other people with the same issues.

[crash-2020-10-17_18.30.49-client.txt](https://github.com/Laike-Endaril/Dynamic-Stealth/files/5396853/crash-2020-10-17_18.30.49-client.txt)

[crash-2020-10-17_18.11.24-client.txt](https://github.com/Laike-Endaril/Dynamic-Stealth/files/5396854/crash-2020-10-17_18.11.24-client.txt)

This has to do with the On Point HUD Issue. From the crash reports.

**Comment by Laike-Endaril** [comment]
The crashes should now be fixed in the latest release (109).  Not sure if the cross-mod render issues are fixed or not.  Tell me what happens if / when you try it.

**Comment by Heaveness** [comment]
Oh no! I just rolled out my update for my mod-pack without OPHUD until it gets fixed. I won't be updating my mod-pack for a long while. Luckily I can test it for my new update that I am working on. Thanks a lot for the hard work! I will let you know if it is fixed or not. It's a bit of a hard crash to replicate since it tends to happen at random.

**Comment by Laike-Endaril** [comment]
Going to close this for now, but I'll see any comments if the issue happens after a mod update
