### ISSUE TITLE
Some sort of crashing issue

### ISSUE THREAD

**Issue by thedeerirty** [Laike-Endaril/Dynamic-Stealth#114]
Hi, I am experiencing a crash that the report traces to this mod? I'm not sure what exactly is causing this crash, but it always seems to happen when I remove a mod (not this one) and then try to load a world when that mod is removed. Going back to an older save didn't seem to help either. 
[crash-2020-10-28_16.30.31-server.txt](https://github.com/Laike-Endaril/Dynamic-Stealth/files/5454687/crash-2020-10-28_16.30.31-server.txt)

**Comment by Laike-Endaril** [comment]
You certainly have something strange going on, though I don't know exactly what.  If you can send me the full log file next time this happens, I can probably do a better job of identifying the issue.

The top-level error listed in the crash report...
java.lang.NoClassDefFoundError: com/fantasticsource/dynamicstealth/compat/CompatDissolution
...should be impossible, as this class is packaged in the DS jar, but there may be an underlying cause listed only in the full log

**Comment by thedeerirty** [comment]
Dissolution; that's the mod about possession, correct? I shouldn't have that in my modpack anymore; I removed it before creating the world, and didn't re-add it. 

I'll try to load the world again, and I can send the latest.log after it crash,

Also, my bad on the late reply.

**Comment by Laike-Endaril** [comment]
If this is still a thing, send me a full log containing the crash (it will be latest.log if it crashed on the most recent run).  The crash report doesn't always tell the whole story.
