### ISSUE TITLE
Hand Mirror Crash with Potioncore and Better HUD

### ISSUE THREAD

**Issue by Heaveness** [Laike-Endaril/Dynamic-Stealth#115]
I had a crash with these two mods when using the Hand Mirror in survival. No issues using it in Creative mode since it doesn't factor in a lot of elements. So here is the crash report! Might be something wrong with the rendering with those mods colliding with DS hand mirror.

[crash-2020-10-30_15.43.55-client.txt](https://github.com/Laike-Endaril/Dynamic-Stealth/files/5467295/crash-2020-10-30_15.43.55-client.txt)

**Comment by Laike-Endaril** [comment]
The root cause lies in the Potion Core mod.  They forgot to check whether the current camera entity was an instance of EntityLivingBase before casting.

I suggest posting a thread on their issue tracker and referencing this issue, as they'd have to fix it on their end for a proper solution.
