### ISSUE TITLE
Bluescreen

### ISSUE THREAD

**Issue by Taknax** [Laike-Endaril/Dynamic-Stealth#117]
I got a bluescreen. :)
Not in the traditional way.
Also i got a bluescreen, but i can hear the entitys in the backround, and if i open the inventor i can see the cursor. Its not crashing and their is no crashlog.

I use 1.12.2 with the latest forge.

**Comment by Laike-Endaril** [comment]
Not completely sure what you mean, but...

Sounds like it could be a shader mod not properly handling the (vanilla) glow effect used by DS.  If so, one option is to find the shader mod and disable it / get a different one

Other solution...

Try going to the DS config and changing
client settings -> HUD -> targeting HUD style -> glow
to false

If that fixes the issue, you might also need to avoid the soul sight potion effect.  Go to
server settings -> interactions -> assassination (melee) -> attacker effects
and remove the line with soulsight

**Comment by Laike-Endaril** [comment]
(Based on private messages, I believe this is resolved; reply here if not)
