### ISSUE TITLE
a lot of crashes

### ISSUE THREAD

**Issue by xelotex** [Laike-Endaril/Dynamic-Stealth#118]
[crash report.zip](https://github.com/Laike-Endaril/Dynamic-Stealth/files/5562843/crash.report.zip)

**Comment by Laike-Endaril** [comment]
This is the same as one of the errors in another active thread, so I'll point you to it and close this one.

Let me point you to a specific post in the thread.  It contains an indev version of DS.  Try downloading it and see if it solves your issue completely, or if a different error pops up:
[https://github.com/Laike-Endaril/Dynamic-Stealth/issues/116#issuecomment-727279022](https://github.com/Laike-Endaril/Dynamic-Stealth/issues/116#issuecomment-727279022)

(Please respond in that thread, to keep related info in one place)
