### ISSUE TITLE
Techguns mobs ignore attacks

### ISSUE THREAD

**Issue by DevTimur** [Laike-Endaril/Dynamic-Stealth#12]
Can you please check why Techguns mobs ignore attack.
https://github.com/pWn3d1337/Techguns2

**Comment by Laike-Endaril** [comment]
Ah yes, techgun mobs cancel the LivingHurtEvent on themselves after doing some processing...I found out about this a little while back while helping debug compatibility between their mod and techguns.

My mod needs to be the last one to process the LivingHurtEvent if possible, but I should be able to work around this somehow.  I'll post here if I release a version with a fix.  Thanks for the report!

**Comment by DevTimur** [comment]
It is so amazing to see active developer. )

**Comment by Laike-Endaril** [comment]
XD

Admittedly my activity has been slightly less lately, but I will *probably* have this fixed no later than sometime this weekend (hopefully sooner)

**Comment by Laike-Endaril** [comment]
I forgot to mention the issue when doing the commit, but when I release version 036 this should be fixed

**Comment by Laike-Endaril** [comment]
Fixed in latest release (036)
