### ISSUE TITLE
[Request] Level Up Stealth Compatibility

### ISSUE THREAD

**Issue by Ameranth** [Laike-Endaril/Dynamic-Stealth#120]
Hello and thank you for your work!

If possible, allowing [Level Up's](https://www.curseforge.com/minecraft/mc-mods/level-up) stealth "levels" to improve stealth with this mod would be wonderful!

**Comment by Laike-Endaril** [comment]
This will be available next release (113).

**Comment by Ameranth** [comment]
Can't wait! Thank you again!

**Comment by Laike-Endaril** [comment]
This is now available in the latest release (113)
