### ISSUE TITLE
[suggestion/bug?] dynamic lights

### ISSUE THREAD

**Issue by derplordofdeath** [Laike-Endaril/Dynamic-Stealth#127]
Is it possible to make hand held lights count as a "light source" for instance if I have optifine on and I have dynamic lights on as well could the light that emits from my torch count as a light. because currently if I have dynamic lights on I can walk up to a mob in a pitch black cave and the mob cant see me but to me the whole place is lit up and it should see me

P.S I have been abusing the fuck out of this trick. forgive me

**Comment by Laike-Endaril** [comment]
See the main issue here: https://github.com/Laike-Endaril/Dynamic-Stealth/issues/75

(Closing this since it's covered by another open issue)
