### ISSUE TITLE
Dynamic Stealth Mod 0.36 make a other mod not playable

### ISSUE THREAD

**Issue by Titoo8899** [Laike-Endaril/Dynamic-Stealth#13]
Hi,
your newest version 0.36 bring a bug what for a other mod not cool is. I have 2 pictures of the statues-rechiseled in this link show this and you see that I mean.

Copy the Link and paste in a new tap. 
Link:[https://github.com/Lemonszz/Statues/issues/6](url)

**Comment by Laike-Endaril** [comment]
Interesting, I'll run some tests and see what I can find.

**Comment by Laike-Endaril** [comment]
Fixed in version 037
