### ISSUE TITLE
Incompatible with LuCrafts' "particle" effects that imitates an entity

### ISSUE THREAD

**Issue by rfwainug** [Laike-Endaril/Dynamic-Stealth#14]
Title says it all, though it's just a hunch. Here instead is the log.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  GenderLoadingPlugin ([1.12.2]Gender-1.2.9.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.4.jar)
  CreativePatchingLoader (CreativeCore_v1.9.37_mc1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  HCASM (HammerCore-1.12.2-2.0.4.1.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 1/28/19 2:11 AM
Description: Exception in server tick loop

java.lang.ClassCastException: lucraft.mods.lucraftcore.superpowers.effects.EffectTrail$EntityTrail cannot be cast to net.minecraft.entity.EntityLiving
	at com.fantasticsource.dynamicstealth.common.DynamicStealth.entityCollision(DynamicStealth.java:200)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_120_DynamicStealth_entityCollision_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3754348368 bytes (3580 MB) / 5704253440 bytes (5440 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2784 89 mods loaded, 89 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                   | Version                | Source                                                   | Signature                                |
	|:------ |:------------------------------------ |:---------------------- |:-------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                            | 1.12.2                 | minecraft.jar                                            | None                                     |
	| LCHIJA | mcp                                  | 9.42                   | minecraft.jar                                            | None                                     |
	| LCHIJA | FML                                  | 8.0.99.99              | forge-1.12.2-14.23.5.2784.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                | 14.23.5.2784           | forge-1.12.2-14.23.5.2784.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy                    | 1.0.0                  | minecraft.jar                                            | None                                     |
	| LCHIJA | passableleavescore                   | 1.0.0                  | minecraft.jar                                            | None                                     |
	| LCHIJA | gender                               | 1.2.9                  | [1.12.2]Gender-1.2.9.jar                                 | None                                     |
	| LCHIJA | additionalbanners                    | 1.1.76                 | AdditionalBanners-1.12.2-1.1.76.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | alcatrazcore                         | 1.0.3                  | alcatrazcore-1.0.3.jar                                   | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCHIJA | backstab                             | 1.0.3                  | backstab-1.12.2-1.0.3.jar                                | None                                     |
	| LCHIJA | badmobs                              | 1.1.36                 | BadMobs-1.12.2-1.1.36.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | baubles                              | 1.5.2                  | Baubles-1.12-1.5.2.jar                                   | None                                     |
	| LCHIJA | betteranimals                        | 3.1                    | betteranimals-3.1.jar                                    | None                                     |
	| LCHIJA | betteranimalsplus                    | 4.1.0                  | betteranimalsplus-4.1.0.jar                              | None                                     |
	| LCHIJA | bettercombatmod                      | 1.5.6                  | BetterCombat-1.12.2-1.5.6.jar                            | None                                     |
	| LCHIJA | jei                                  | 4.14.4.261             | jei_1.12.2-4.14.4.261.jar                                | None                                     |
	| LCHIJA | botania                              | r1.10-358              | Botania+r1.10-358.jar                                    | None                                     |
	| LCHIJA | redstoneflux                         | 2.1.0                  | RedstoneFlux-1.12-2.1.0.6-universal.jar                  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                             | 4.6.1                  | CoFHCore-1.12.2-4.6.1.22-universal.jar                   | None                                     |
	| LCHIJA | crafttweaker                         | 4.1.14                 | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJA | mantle                               | 1.12-1.3.3.39          | Mantle-1.12-1.3.3.39.jar                                 | None                                     |
	| LCHIJA | tconstruct                           | 1.12.2-2.12.0.115      | TConstruct-1.12.2-2.12.0.115.jar                         | None                                     |
	| LCHIJA | conarm                               | 1.2.3                  | conarm-1.12.2-1.2.3.jar                                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | cosmeticarmorreworked                | 1.12.2-v4              | CosmeticArmorReworked-1.12.2-v4.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | cosmeticarmorreworked|tombmanygraves | 1.12.2-v4              | CosmeticArmorReworked-1.12.2-v4.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | ctgui                                | 1.0.0                  | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJA | crafttweakerjei                      | 2.0.2                  | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJA | creativecore                         | 1.9.9                  | CreativeCore_v1.9.37_mc1.12.2.jar                        | None                                     |
	| LCHIJA | cyberware                            | 0.2.10.15              | cyberware-1.12.2-0.2.10.15.jar                           | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LCHIJA | cyclopscore                          | 1.0.1                  | CyclopsCore-1.12.2-1.0.1.jar                             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | dynamicstealth                       | 1.12.2.037             | DynamicStealth-1.12.2.037 (1).jar                        | None                                     |
	| LCHIJA | epicsiegemod                         | 13.163                 | EpicSiegeMod-13.163.jar                                  | None                                     |
	| LCHIJA | everlastingabilities                 | 1.3.19                 | EverlastingAbilities-1.12.2-1.3.19.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | mtlib                                | 3.0.5                  | MTLib-3.0.5.jar                                          | None                                     |
	| LCHIJA | extrabotany                          | 50                     | ExtraBotany-r1.1-50.jar                                  | None                                     |
	| LCHIJA | fastleafdecay                        | v14                    | FastLeafDecay-v14.jar                                    | None                                     |
	| LCHIJA | forgelin                             | 1.8.2                  | Forgelin-1.8.2.jar                                       | None                                     |
	| LCHIJA | ftblib                               | 5.4.0.73               | FTBLib-5.4.0.73.jar                                      | None                                     |
	| LCHIJA | ftbutilities                         | 5.3.0.68               | FTBUtilities-5.3.0.68.jar                                | None                                     |
	| LCHIJA | gravestone                           | 1.10.2                 | gravestone-1.10.2.jar                                    | None                                     |
	| LCHIJA | guideapi                             | 1.12-2.1.8-63          | Guide-API-1.12-2.1.8-63.jar                              | None                                     |
	| LCHIJA | hammercore                           | 2.0.4.1                | HammerCore-1.12.2-2.0.4.1.jar                            | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | lucraftcore                          | 1.12.2-2.3.4           | LucraftCore-1.12.2-2.3.4.jar                             | None                                     |
	| LCHIJA | heroesexpansion                      | 1.12.2-1.2.3           | HeroesExpansion-1.12.2-1.2.3.jar                         | None                                     |
	| LCHIJA | howlingmoon                          | 0.9                    | howlingmooncustom.jar                                    | None                                     |
	| LCHIJA | ichunutil                            | 7.1.4                  | iChunUtil-1.12.2-7.1.4.jar                               | None                                     |
	| LCHIJA | improvableskills                     | 3.6.0r                 | ImprovableSkills-1.12.2-3.6.0r.jar                       | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | improvedbackpacks                    | 1.12.2-1.4.0.0         | ImprovedBackpacks-1.12.2-1.4.0.0.jar                     | None                                     |
	| LCHIJA | infernalmobs                         | 1.7.5                  | InfernalMobs-1.12.2.jar                                  | None                                     |
	| LCHIJA | jepb                                 | 1.2.1                  | jepb-1.12-1.2.1.jar                                      | None                                     |
	| LCHIJA | librarianlib                         | 4.15                   | librarianlib-1.12.2-4.15.jar                             | None                                     |
	| LCHIJA | locks                                | 2.2                    | Locks-2.2.jar                                            | None                                     |
	| LCHIJA | manatweaks                           | 1.3                    | manatweaks-1.3.jar                                       | None                                     |
	| LCHIJA | radixcore                            | 1.12.x-2.2.1           | RadixCore-1.12.x-2.2.1-universal.jar                     | None                                     |
	| LCHIJA | mca                                  | 1.12.2-5.3.1           | MCA-1.12.x-5.3.1-universal.jar                           | None                                     |
	| LCHIJA | metallurgy                           | 0.0.5                  | Metallurgy-4-Reforged-0.0.5.jar                          | None                                     |
	| LCHIJA | mobamputation                        | 7.0.0                  | MobAmputation-1.12.2-7.0.0.jar                           | None                                     |
	| LCHIJA | moreplayermodels                     | 1.12.2                 | MorePlayerModels_1.12.2(18jan18).jar                     | None                                     |
	| LCHIJA | naturalpledge                        | 3.0.2                  | NaturalPledge-r3.0.2.jar                                 | None                                     |
	| LCHIJA | opframe                              | 1.4.0                  | OnlinePicFrame_v1.4.23_mc1.12.2.jar                      | None                                     |
	| LCHIJA | parry                                | 1.0                    | parry-1.0-hotfix.jar                                     | None                                     |
	| LCHIJA | playerrevive                         | 1.0                    | PlayerRevive_v1.2.23_mc1.12.2.jar                        | None                                     |
	| LCHIJA | plumedbelt                           | 1.0.1                  | plumedbelt-1.0.1.jar                                     | None                                     |
	| LCHIJA | rustic                               | 1.0.15                 | rustic-1.0.15.jar                                        | None                                     |
	| LCHIJA | immersiveengineering                 | 0.12-88                | ImmersiveEngineering-0.12-88.jar                         | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | primal                               | 0.6.104                | PrimalCore-1.12.2-0.6.104.jar                            | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LCHIJA | ra                                   | 1.12.2-1.0.0           | Recycle+Armor-1.12.2-1.2.1.jar                           | None                                     |
	| LCHIJA | redstonepaste                        | 1.7.5                  | redstonepaste-mc1.12-1.7.5.jar                           | None                                     |
	| LCHIJA | rewired                              | 1.12.2                 | ReWIRED-1.0.4.jar                                        | None                                     |
	| LCHIJA | subcommonlib                         | 1.2.0.1                | subcommonlib-sublib-1.12.2-1.2.0.4.jar                   | None                                     |
	| LCHIJA | rpginventory                         | 1.12.2                 | rpginventory-1.12-5.3.0.0.jar                            | None                                     |
	| LCHIJA | tiffitlib                            | 1.0.3                  | tiffitlib-1.0.3.jar                                      | None                                     |
	| LCHIJA | sanity                               | 1.0.3                  | sanity-1.0.3.jar                                         | None                                     |
	| LCHIJA | special_ai                           | 1.1.3                  | Special_AI_v1.0.jar                                      | None                                     |
	| LCHIJA | stg                                  | 1.12.2-1.2.3           | stg-1.12.2-1.2.3.jar                                     | None                                     |
	| LCHIJA | tails                                | 1.12-1.10.0            | Tails-1.12-1.10.0.jar                                    | None                                     |
	| LCHIJA | tinkerscompendium                    | 1.4.2.21               | tinkersdefense-1.4.2.21.jar                              | None                                     |
	| LCHIJA | tinkersarsenal                       | 0.5                    | tinkersarsenal-0.5.jar                                   | None                                     |
	| LCHIJA | tipthescales                         | 1.0.3                  | TipTheScales-1.12.2-1.0.3.jar                            | None                                     |
	| LCHIJA | torohealthmod                        | 1.12.2-11              | torohealth-1.12.2-11.jar                                 | None                                     |
	| LCHIJA | toroquest                            | 1.12.2-5.3             | toroquest-1.12.2-5.3.jar                                 | None                                     |
	| LCHIJA | vampire                              | 0.0.2B                 | vampire-0.0.2B.jar                                       | None                                     |
	| LCHIJA | vampirism                            | 1.4.9                  | Vampirism-1.12.2-1.4.9.jar                               | None                                     |
	| LCHIJA | teamlapen-lib                        | 1.4.9                  | Vampirism-1.12.2-1.4.9.jar                               | None                                     |
	| LCHIJA | vampirism_integrations               | vampirism_integrations | VampirismIntegrations-1.12.2-1.1.0-alpha+12-09-22-44.jar | None                                     |
	| LCHIJA | walljump                             | 1.12.2-1.2.1           | walljump-1.12.2-1.2.1.jar                                | None                                     |
	| LCHIJA | worleycaves                          | 1.3.0                  | worleycaves-1.3.0.jar                                    | None                                     |
	| LCHIJA | passableleaves                       | 2.0.0                  | PassableLeaves-1.12.2-2.0.0.jar                          | None                                     |
	| LCHIJA | librarianliblate                     | 4.15                   | librarianlib-1.12.2-4.15.jar                             | None                                     |

	Loaded coremods (and transformers): 
GenderLoadingPlugin ([1.12.2]Gender-1.2.9.jar)
  com.github.ipixeli.gender.coremod.GenderClassTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  teamrtg.passableleaves.asm.PassableLeavesTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.4.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
CreativePatchingLoader (CreativeCore_v1.9.37_mc1.12.2.jar)
  
ForgelinPlugin (Forgelin-1.8.2.jar)
  
HCASM (HammerCore-1.12.2-2.0.4.1.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 5356 names; 2780 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
Dependent Mods:
    -Improvable Skills (improvableskills) @3.6.0r

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['starwolf62'/468, l='New World', x=-218.06, y=73.26, z=158.10]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Laike-Endaril** [comment]
Looks like I made a general mistake in my recent touch detection code, so thanks for posting this!  I'll try to release a fix by tonight or tomorrow.

Edit: Luckily this was an extremely easy fix.  I will release a new version with the fix as soon as I finish the new feature I'm working on.  I *think* I've also made a change to prevent the particles from triggering entities' touch detection.

**Comment by Laike-Endaril** [comment]
This should now be fixed in the latest release (038)
