### ISSUE TITLE
Caught exception with immersive engineering (donno if I send this one to you or them, but it only happened after your latest update)

### ISSUE THREAD

**Issue by rfwainug** [Laike-Endaril/Dynamic-Stealth#15]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  GenderLoadingPlugin ([1.12.2]Gender-1.2.9.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.4.jar)
  CreativePatchingLoader (CreativeCore_v1.9.37_mc1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.6.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  HCASM (HammerCore-1.12.2-2.0.4.1.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 1/29/19 7:15 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Engineering (immersiveengineering)
Caused by: java.lang.NullPointerException
	at blusunrize.immersiveengineering.common.IEContent.postInit(IEContent.java:1070)
	at blusunrize.immersiveengineering.ImmersiveEngineering.postInit(ImmersiveEngineering.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3428534976 bytes (3269 MB) / 5502926848 bytes (5248 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2784 90 mods loaded, 90 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                   | Version                | Source                                                   | Signature                                |
	|:----- |:------------------------------------ |:---------------------- |:-------------------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft                            | 1.12.2                 | minecraft.jar                                            | None                                     |
	| LCHIJ | mcp                                  | 9.42                   | minecraft.jar                                            | None                                     |
	| LCHIJ | FML                                  | 8.0.99.99              | forge-1.12.2-14.23.5.2784.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                                | 14.23.5.2784           | forge-1.12.2-14.23.5.2784.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | creativecoredummy                    | 1.0.0                  | minecraft.jar                                            | None                                     |
	| LCHIJ | passableleavescore                   | 1.0.0                  | minecraft.jar                                            | None                                     |
	| LCHIJ | dsurroundcore                        |                        | minecraft.jar                                            | None                                     |
	| LCHIJ | gender                               | 1.2.9                  | [1.12.2]Gender-1.2.9.jar                                 | None                                     |
	| LCHIJ | additionalbanners                    | 1.1.76                 | AdditionalBanners-1.12.2-1.1.76.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJ | alcatrazcore                         | 1.0.3                  | alcatrazcore-1.0.3.jar                                   | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCHIJ | backstab                             | 1.0.3                  | backstab-1.12.2-1.0.3.jar                                | None                                     |
	| LCHIJ | badmobs                              | 1.1.36                 | BadMobs-1.12.2-1.1.36.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJ | baubles                              | 1.5.2                  | Baubles-1.12-1.5.2.jar                                   | None                                     |
	| LCHIJ | betteranimals                        | 3.1                    | betteranimals-3.1.jar                                    | None                                     |
	| LCHIJ | betteranimalsplus                    | 4.1.0                  | betteranimalsplus-4.1.0.jar                              | None                                     |
	| LCHIJ | bettercombatmod                      | 1.5.6                  | BetterCombat-1.12.2-1.5.6.jar                            | None                                     |
	| LCHIJ | jei                                  | 4.14.4.261             | jei_1.12.2-4.14.4.261.jar                                | None                                     |
	| LCHIJ | botania                              | r1.10-358              | Botania+r1.10-358.jar                                    | None                                     |
	| LCHIJ | redstoneflux                         | 2.1.0                  | RedstoneFlux-1.12-2.1.0.6-universal.jar                  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJ | cofhcore                             | 4.6.1                  | CoFHCore-1.12.2-4.6.1.22-universal.jar                   | None                                     |
	| LCHIJ | crafttweaker                         | 4.1.14                 | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJ | mantle                               | 1.12-1.3.3.39          | Mantle-1.12-1.3.3.39.jar                                 | None                                     |
	| LCHIJ | tconstruct                           | 1.12.2-2.12.0.115      | TConstruct-1.12.2-2.12.0.115.jar                         | None                                     |
	| LCHIJ | conarm                               | 1.2.3                  | conarm-1.12.2-1.2.3.jar                                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJ | cosmeticarmorreworked                | 1.12.2-v4              | CosmeticArmorReworked-1.12.2-v4.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJ | cosmeticarmorreworked|tombmanygraves | 1.12.2-v4              | CosmeticArmorReworked-1.12.2-v4.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJ | ctgui                                | 1.0.0                  | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJ | crafttweakerjei                      | 2.0.2                  | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJ | creativecore                         | 1.9.9                  | CreativeCore_v1.9.37_mc1.12.2.jar                        | None                                     |
	| LCHIJ | cyberware                            | 0.2.10.15              | cyberware-1.12.2-0.2.10.15.jar                           | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LCHIJ | cyclopscore                          | 1.0.1                  | CyclopsCore-1.12.2-1.0.1.jar                             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJ | dynamicstealth                       | 1.12.2.038             | DynamicStealth-1.12.2.038.jar                            | None                                     |
	| LCHIJ | epicsiegemod                         | 13.163                 | EpicSiegeMod-13.163.jar                                  | None                                     |
	| LCHIJ | everlastingabilities                 | 1.3.19                 | EverlastingAbilities-1.12.2-1.3.19.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJ | mtlib                                | 3.0.5                  | MTLib-3.0.5.jar                                          | None                                     |
	| LCHIJ | extrabotany                          | 50                     | ExtraBotany-r1.1-50.jar                                  | None                                     |
	| LCHIJ | fastleafdecay                        | v14                    | FastLeafDecay-v14.jar                                    | None                                     |
	| LCHIJ | forgelin                             | 1.8.2                  | Forgelin-1.8.2.jar                                       | None                                     |
	| LCHIJ | ftblib                               | 5.4.0.73               | FTBLib-5.4.0.73.jar                                      | None                                     |
	| LCHIJ | ftbutilities                         | 5.3.0.68               | FTBUtilities-5.3.0.68.jar                                | None                                     |
	| LCHIJ | gravestone                           | 1.10.2                 | gravestone-1.10.2.jar                                    | None                                     |
	| LCHIJ | guideapi                             | 1.12-2.1.8-63          | Guide-API-1.12-2.1.8-63.jar                              | None                                     |
	| LCHIJ | hammercore                           | 2.0.4.1                | HammerCore-1.12.2-2.0.4.1.jar                            | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJ | lucraftcore                          | 1.12.2-2.3.4           | LucraftCore-1.12.2-2.3.4.jar                             | None                                     |
	| LCHIJ | heroesexpansion                      | 1.12.2-1.2.3           | HeroesExpansion-1.12.2-1.2.3.jar                         | None                                     |
	| LCHIJ | howlingmoon                          | 0.9                    | howlingmooncustom.jar                                    | None                                     |
	| LCHIJ | ichunutil                            | 7.1.4                  | iChunUtil-1.12.2-7.1.4.jar                               | None                                     |
	| LCHIJ | improvableskills                     | 3.6.0r                 | ImprovableSkills-1.12.2-3.6.0r.jar                       | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJ | improvedbackpacks                    | 1.12.2-1.4.0.0         | ImprovedBackpacks-1.12.2-1.4.0.0.jar                     | None                                     |
	| LCHIJ | infernalmobs                         | 1.7.5                  | InfernalMobs-1.12.2.jar                                  | None                                     |
	| LCHIJ | jepb                                 | 1.2.1                  | jepb-1.12-1.2.1.jar                                      | None                                     |
	| LCHIJ | librarianlib                         | 4.15                   | librarianlib-1.12.2-4.15.jar                             | None                                     |
	| LCHIJ | locks                                | 2.2                    | Locks-2.2.jar                                            | None                                     |
	| LCHIJ | manatweaks                           | 1.3                    | manatweaks-1.3.jar                                       | None                                     |
	| LCHIJ | radixcore                            | 1.12.x-2.2.1           | RadixCore-1.12.x-2.2.1-universal.jar                     | None                                     |
	| LCHIJ | mca                                  | 1.12.2-5.3.1           | MCA-1.12.x-5.3.1-universal.jar                           | None                                     |
	| LCHIJ | metallurgy                           | 0.0.5                  | Metallurgy-4-Reforged-0.0.5.jar                          | None                                     |
	| LCHIJ | mobamputation                        | 7.0.0                  | MobAmputation-1.12.2-7.0.0.jar                           | None                                     |
	| LCHIJ | moreplayermodels                     | 1.12.2                 | MorePlayerModels_1.12.2(18jan18).jar                     | None                                     |
	| LCHIJ | naturalpledge                        | 3.0.2                  | NaturalPledge-r3.0.2.jar                                 | None                                     |
	| LCHIJ | opframe                              | 1.4.0                  | OnlinePicFrame_v1.4.23_mc1.12.2.jar                      | None                                     |
	| LCHIJ | parry                                | 1.0                    | parry-1.0-hotfix.jar                                     | None                                     |
	| LCHIJ | plumedbelt                           | 1.0.1                  | plumedbelt-1.0.1.jar                                     | None                                     |
	| LCHIJ | ra                                   | 1.12.2-1.0.0           | Recycle+Armor-1.12.2-1.2.1.jar                           | None                                     |
	| LCHIJ | redstonepaste                        | 1.7.5                  | redstonepaste-mc1.12-1.7.5.jar                           | None                                     |
	| LCHIJ | rewired                              | 1.12.2                 | ReWIRED-1.0.4.jar                                        | None                                     |
	| LCHIJ | subcommonlib                         | 1.2.0.1                | subcommonlib-sublib-1.12.2-1.2.0.4.jar                   | None                                     |
	| LCHIJ | rpginventory                         | 1.12.2                 | rpginventory-1.12-5.3.0.0.jar                            | None                                     |
	| LCHIJ | rustic                               | 1.0.15                 | rustic-1.0.15.jar                                        | None                                     |
	| LCHIJ | tiffitlib                            | 1.0.3                  | tiffitlib-1.0.3.jar                                      | None                                     |
	| LCHIJ | sanity                               | 1.0.3                  | sanity-1.0.3.jar                                         | None                                     |
	| LCHIJ | special_ai                           | 1.1.3                  | Special_AI_v1.0.jar                                      | None                                     |
	| LCHIJ | stg                                  | 1.12.2-1.2.3           | stg-1.12.2-1.2.3.jar                                     | None                                     |
	| LCHIJ | tails                                | 1.12-1.10.0            | Tails-1.12-1.10.0.jar                                    | None                                     |
	| LCHIJ | tinkerscompendium                    | 1.4.2.21               | tinkersdefense-1.4.2.21.jar                              | None                                     |
	| LCHIJ | tinkersarsenal                       | 0.5                    | tinkersarsenal-0.5.jar                                   | None                                     |
	| LCHIJ | tipthescales                         | 1.0.3                  | TipTheScales-1.12.2-1.0.3.jar                            | None                                     |
	| LCHIJ | torohealthmod                        | 1.12.2-11              | torohealth-1.12.2-11.jar                                 | None                                     |
	| LCHIJ | toroquest                            | 1.12.2-5.3             | toroquest-1.12.2-5.3.jar                                 | None                                     |
	| LCHIJ | vampire                              | 0.0.2B                 | vampire-0.0.2B.jar                                       | None                                     |
	| LCHIJ | vampirism                            | 1.4.9                  | Vampirism-1.12.2-1.4.9.jar                               | None                                     |
	| LCHIJ | teamlapen-lib                        | 1.4.9                  | Vampirism-1.12.2-1.4.9.jar                               | None                                     |
	| LCHIJ | vampirism_integrations               | vampirism_integrations | VampirismIntegrations-1.12.2-1.1.0-alpha+12-09-22-44.jar | None                                     |
	| LCHIJ | walljump                             | 1.12.2-1.2.1           | walljump-1.12.2-1.2.1.jar                                | None                                     |
	| LCHIJ | worleycaves                          | 1.3.0                  | worleycaves-1.3.0.jar                                    | None                                     |
	| LCHIJ | dsurround                            | 3.4.10.6               | DynamicSurroundings-1.12.2-3.4.10.6.jar                  | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJ | presets                              | 3.4.10.6               | DynamicSurroundings-1.12.2-3.4.10.6.jar                  | None                                     |
	| LCHIE | immersiveengineering                 | 0.12-88                | ImmersiveEngineering-0.12-88.jar                         | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHI  | passableleaves                       | 2.0.0                  | PassableLeaves-1.12.2-2.0.0.jar                          | None                                     |
	| LCHI  | librarianliblate                     | 4.15                   | librarianlib-1.12.2-4.15.jar                             | None                                     |

	Loaded coremods (and transformers): 
GenderLoadingPlugin ([1.12.2]Gender-1.2.9.jar)
  com.github.ipixeli.gender.coremod.GenderClassTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  teamrtg.passableleaves.asm.PassableLeavesTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.4.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
CreativePatchingLoader (CreativeCore_v1.9.37_mc1.12.2.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.6.jar)
  org.blockartistry.DynSurround.asm.Transformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
HCASM (HammerCore-1.12.2-2.0.4.1.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 399.07' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 3390 names; 1718 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
Dependent Mods:
    -Improvable Skills (improvableskills) @3.6.0r

**Comment by Laike-Endaril** [comment]
Interesting.  I've found the issue, but am still deciding on the best solution.

It has to do with their code for setting up potion mixing, and my new soul sight potion recipe, which returns its result dynamically instead of storing a predefined result.  I think I can set my output in a way that will fix this without breaking my own recipe.

**Comment by Laike-Endaril** [comment]
I've released a new version which should fix this
