### ISSUE TITLE
Incompatibility with Special AI

### ISSUE THREAD

**Issue by rfwainug** [Laike-Endaril/Dynamic-Stealth#18]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 1/31/19 4:09 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.util.math.BlockPos.<init>(SourceFile:41)
	at net.minecraft.pathfinding.PathNavigateGround.func_75494_a(SourceFile:73)
	at net.minecraft.pathfinding.PathNavigate.func_75497_a(SourceFile:147)
	at toast.specialAI.ai.EntityAIAttackMeleePassive.func_75246_d(EntityAIAttackMeleePassive.java:81)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2351)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2171)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.util.math.BlockPos.<init>(SourceFile:41)
	at net.minecraft.pathfinding.PathNavigateGround.func_75494_a(SourceFile:73)
	at net.minecraft.pathfinding.PathNavigate.func_75497_a(SourceFile:147)
	at toast.specialAI.ai.EntityAIAttackMeleePassive.func_75246_d(EntityAIAttackMeleePassive.java:81)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2351)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2171)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: minecraft:villager (net.minecraft.entity.passive.EntityVillager)
	Entity ID: 4223
	Entity Name: Villager
	Entity's Exact location: -378.48, 74.00, 374.01
	Entity's Block location: World: (-379,74,374), Chunk: (at 5,4,6 in -24,23; contains blocks -384,0,368 to -369,255,383), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, -0.10
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Copy of Copy of New World
	All players: 1 total; [EntityPlayerMP['starwolf62'/1852, l='Copy of Copy of New World', x=-413.54, y=74.04, z=365.18]]
	Chunk stats: ServerChunkCache: 905 Drop: 0
	Level seed: -4431864475954182016
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-132,64,224), Chunk: (at 12,4,0 in -9,14; contains blocks -144,0,224 to -129,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2315 game time, 13637 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 26491 (now: false), thunder time: 97641 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1894777560 bytes (1807 MB) / 3657433088 bytes (3488 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2784 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                        | Signature                                |
	|:------ |:-------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2784.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge          | 14.23.5.2784 | forge-1.12.2-14.23.5.2784.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | dynamicstealth | 1.12.2.041   | DynamicStealth-1.12.2.041.jar | None                                     |
	| LCHIJA | special_ai     | 1.1.3        | Special_AI_v1.0.jar           | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['starwolf62'/1852, l='Copy of Copy of New World', x=-413.54, y=74.04, z=365.18]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Laike-Endaril** [comment]
I've released a new version (042) which should fix this, but I'll wait for your new results before closing

**Comment by rfwainug** [comment]
No dice.
----------------------------------------------------------------------------------------------
---- Minecraft Crash Report ----

WARNING: coremods are present:
  GenderLoadingPlugin ([1.12.2]Gender-1.2.9.jar)
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.4.jar)
  CreativePatchingLoader (CreativeCore_v1.9.37_mc1.12.2.jar)
  EmoticonsCore (emoticons-0.2.1-1.12.2.jar)
  HCASM (HammerCore-1.12.2-2.0.4.1.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 1/31/19 11:02 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.util.math.BlockPos.<init>(SourceFile:41)
	at net.minecraft.pathfinding.PathNavigateGround.func_75494_a(SourceFile:73)
	at net.minecraft.pathfinding.PathNavigate.func_75497_a(SourceFile:147)
	at toast.specialAI.ai.EntityAIAttackMeleePassive.func_75246_d(EntityAIAttackMeleePassive.java:81)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2351)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2171)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.util.math.BlockPos.<init>(SourceFile:41)
	at net.minecraft.pathfinding.PathNavigateGround.func_75494_a(SourceFile:73)
	at net.minecraft.pathfinding.PathNavigate.func_75497_a(SourceFile:147)
	at toast.specialAI.ai.EntityAIAttackMeleePassive.func_75246_d(EntityAIAttackMeleePassive.java:81)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2351)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2171)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: minecraft:villager (net.minecraft.entity.passive.EntityVillager)
	Entity ID: 4807
	Entity Name: Villager
	Entity's Exact location: -451.52, 64.00, 381.37
	Entity's Block location: World: (-452,64,381), Chunk: (at 12,4,13 in -29,23; contains blocks -464,0,368 to -449,255,383), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.07, -0.08, -0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Copy of fwainf
	All players: 1 total; [EntityPlayerMP['starwolf62'/2825, l='Copy of fwainf', x=-448.00, y=69.64, z=339.13]]
	Chunk stats: ServerChunkCache: 843 Drop: 0
	Level seed: -5207852501741467608
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-240,64,240), Chunk: (at 0,4,0 in -15,15; contains blocks -240,0,240 to -225,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1601 game time, 13541 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 171065 (now: false), thunder time: 54321 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3859448472 bytes (3680 MB) / 6845104128 bytes (6528 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2784 83 mods loaded, 82 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                   | Version                | Source                                                   | Signature                                |
	|:------ |:------------------------------------ |:---------------------- |:-------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                            | 1.12.2                 | minecraft.jar                                            | None                                     |
	| LCHIJA | mcp                                  | 9.42                   | minecraft.jar                                            | None                                     |
	| LCHIJA | FML                                  | 8.0.99.99              | forge-1.12.2-14.23.5.2784.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                | 14.23.5.2784           | forge-1.12.2-14.23.5.2784.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy                    | 1.0.0                  | minecraft.jar                                            | None                                     |
	| LCHIJA | passableleavescore                   | 1.0.0                  | minecraft.jar                                            | None                                     |
	| LCHIJA | gender                               | 1.2.9                  | [1.12.2]Gender-1.2.9.jar                                 | None                                     |
	| LCHIJA | additionalbanners                    | 1.1.76                 | AdditionalBanners-1.12.2-1.1.76.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | alcatrazcore                         | 1.0.3                  | alcatrazcore-1.0.3.jar                                   | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCHIJA | backstab                             | 1.0.3                  | backstab-1.12.2-1.0.3.jar                                | None                                     |
	| LCHIJA | badmobs                              | 1.1.36                 | BadMobs-1.12.2-1.1.36.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | baubles                              | 1.5.2                  | Baubles-1.12-1.5.2.jar                                   | None                                     |
	| LCHIJA | betteranimals                        | 3.1                    | betteranimals-3.1.jar                                    | None                                     |
	| LCHIJA | betteranimalsplus                    | 4.1.0                  | betteranimalsplus-4.1.0.jar                              | None                                     |
	| LCHIJA | bettercombatmod                      | 1.5.6                  | BetterCombat-1.12.2-1.5.6.jar                            | None                                     |
	| LCHIJA | bionisation3                         | 1.0.6                  | Bionisation3-1.12.2-1.0.6.jar                            | None                                     |
	| LCHIJA | chargeblade                          | 1.0                    | chargeblade-1.0.jar                                      | None                                     |
	| LCHIJA | redstoneflux                         | 2.1.0                  | RedstoneFlux-1.12-2.1.0.6-universal.jar                  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                             | 4.6.1                  | CoFHCore-1.12.2-4.6.1.22-universal.jar                   | None                                     |
	| LCHIJA | crafttweaker                         | 4.1.14                 | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJA | mantle                               | 1.12-1.3.3.39          | Mantle-1.12-1.3.3.39.jar                                 | None                                     |
	| LCHIJA | jei                                  | 4.14.4.261             | jei_1.12.2-4.14.4.261.jar                                | None                                     |
	| LCHIJA | tconstruct                           | 1.12.2-2.12.0.115      | TConstruct-1.12.2-2.12.0.115.jar                         | None                                     |
	| LCHIJA | conarm                               | 1.2.3                  | conarm-1.12.2-1.2.3.jar                                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | cosmeticarmorreworked                | 1.12.2-v4              | CosmeticArmorReworked-1.12.2-v4.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | cosmeticarmorreworked|tombmanygraves | 1.12.2-v4              | CosmeticArmorReworked-1.12.2-v4.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | ctgui                                | 1.0.0                  | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJA | crafttweakerjei                      | 2.0.2                  | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJA | creativecore                         | 1.9.9                  | CreativeCore_v1.9.37_mc1.12.2.jar                        | None                                     |
	| LCHIJA | cyberware                            | 0.2.10.15              | cyberware-1.12.2-0.2.10.15.jar                           | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LCHIJA | cyclopscore                          | 1.0.1                  | CyclopsCore-1.12.2-1.0.1.jar                             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | dynamicstealth                       | 1.12.2.042             | DynamicStealth-1.12.2.042.jar                            | None                                     |
	| LCHIJA | emoticons                            | 0.2.1                  | emoticons-0.2.1-1.12.2.jar                               | None                                     |
	| LCHIJA | epicsiegemod                         | 13.163                 | EpicSiegeMod-13.163.jar                                  | None                                     |
	| LCHIJA | everlastingabilities                 | 1.3.19                 | EverlastingAbilities-1.12.2-1.3.19.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | fastleafdecay                        | v14                    | FastLeafDecay-v14.jar                                    | None                                     |
	| LCHIJA | ftblib                               | 5.4.0.73               | FTBLib-5.4.0.73.jar                                      | None                                     |
	| LCHIJA | ftbutilities                         | 5.3.0.68               | FTBUtilities-5.3.0.68.jar                                | None                                     |
	| LCHIJA | gravestone                           | 1.10.2                 | gravestone-1.10.2.jar                                    | None                                     |
	| LCHIJA | guideapi                             | 1.12-2.1.8-63          | Guide-API-1.12-2.1.8-63.jar                              | None                                     |
	| LCHIJA | hammercore                           | 2.0.4.1                | HammerCore-1.12.2-2.0.4.1.jar                            | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | lucraftcore                          | 1.12.2-2.3.4           | LucraftCore-1.12.2-2.3.4.jar                             | None                                     |
	| LCHIJA | heroesexpansion                      | 1.12.2-1.2.3           | HeroesExpansion-1.12.2-1.2.3.jar                         | None                                     |
	| LCHIJA | howlingmoon                          | 0.9                    | howlingmooncustom.jar                                    | None                                     |
	| LCHIJA | ichunutil                            | 7.1.4                  | iChunUtil-1.12.2-7.1.4.jar                               | None                                     |
	| LCHIJA | improvableskills                     | 3.6.0r                 | ImprovableSkills-1.12.2-3.6.0r.jar                       | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | improvedbackpacks                    | 1.12.2-1.4.0.0         | ImprovedBackpacks-1.12.2-1.4.0.0.jar                     | None                                     |
	| LCHIJA | infernalmobs                         | 1.7.5                  | InfernalMobs-1.12.2.jar                                  | None                                     |
	| LCHIJA | jepb                                 | 1.2.1                  | jepb-1.12-1.2.1.jar                                      | None                                     |
	| LCHIJA | kindredlegacy                        | 1.12.2-1.2.1           | kindredlegacy-1.12.2-1.2.1.jar                           | None                                     |
	| LCHIJA | livingenchantment                    | 3.1.3                  | living_enchantment-3.1.3.jar                             | None                                     |
	| LCHIJA | locks                                | 2.2                    | Locks-2.2.jar                                            | None                                     |
	| LCHIJA | radixcore                            | 1.12.x-2.2.1           | RadixCore-1.12.x-2.2.1-universal.jar                     | None                                     |
	| LCHIJA | mca                                  | 1.12.2-5.3.1           | MCA-1.12.x-5.3.1-universal.jar                           | None                                     |
	| LCHIJA | metallurgy                           | 0.0.5                  | Metallurgy-4-Reforged-0.0.5.jar                          | None                                     |
	| LCHIJA | mobamputation                        | 7.0.0                  | MobAmputation-1.12.2-7.0.0.jar                           | None                                     |
	| LCHIJA | moreplayermodels                     | 1.12.2                 | MorePlayerModels_1.12.2(18jan18).jar                     | None                                     |
	| LCHIJA | mtlib                                | 3.0.5                  | MTLib-3.0.5.jar                                          | None                                     |
	| LCHIJA | opframe                              | 1.4.0                  | OnlinePicFrame_v1.4.23_mc1.12.2.jar                      | None                                     |
	| LCHIJA | parry                                | 1.0                    | parry-1.0-hotfix.jar                                     | None                                     |
	| LCHIJA | ra                                   | 1.12.2-1.0.0           | Recycle+Armor-1.12.2-1.2.1.jar                           | None                                     |
	| LCHIJA | redstonepaste                        | 1.7.5                  | redstonepaste-mc1.12-1.7.5.jar                           | None                                     |
	| LCHIJA | rewired                              | 1.12.2                 | ReWIRED-1.0.4.jar                                        | None                                     |
	| LCHIJA | subcommonlib                         | 1.2.0.1                | subcommonlib-sublib-1.12.2-1.2.0.4.jar                   | None                                     |
	| LCHIJA | rpginventory                         | 1.12.2                 | rpginventory-1.12-5.3.0.0.jar                            | None                                     |
	| LCHIJA | special_ai                           | 1.1.3                  | Special_AI_v1.0.jar                                      | None                                     |
	| LCHIJA | stg                                  | 1.12.2-1.2.3           | stg-1.12.2-1.2.3.jar                                     | None                                     |
	| LCHIJA | tails                                | 1.12-1.10.0            | Tails-1.12-1.10.0.jar                                    | None                                     |
	| LCHIJA | tiffitlib                            | 1.0.3                  | tiffitlib-1.0.3.jar                                      | None                                     |
	| LCHIJA | tinkerscompendium                    | 1.4.2.22.1             | tinkersdefense-1.4.2.22.1.jar                            | None                                     |
	| LCHIJA | tinkersarsenal                       | 0.5                    | tinkersarsenal-0.5.jar                                   | None                                     |
	| LCHIJA | tipthescales                         | 1.0.3                  | TipTheScales-1.12.2-1.0.3.jar                            | None                                     |
	| LCHIJA | torohealthmod                        | 1.12.2-11              | torohealth-1.12.2-11.jar                                 | None                                     |
	| LCHIJA | toroquest                            | 1.12.2-5.3             | toroquest-1.12.2-5.3.jar                                 | None                                     |
	| LCHIJA | vampire                              | 0.0.2B                 | vampire-0.0.2B.jar                                       | None                                     |
	| LCHIJA | vampirism                            | 1.4.9                  | Vampirism-1.12.2-1.4.9.jar                               | None                                     |
	| LCHIJA | teamlapen-lib                        | 1.4.9                  | Vampirism-1.12.2-1.4.9.jar                               | None                                     |
	| LCHIJA | vampirism_integrations               | vampirism_integrations | VampirismIntegrations-1.12.2-1.1.0-alpha+12-09-22-44.jar | None                                     |
	| LCHIJA | walljump                             | 1.12.2-1.2.1           | walljump-1.12.2-1.2.1.jar                                | None                                     |
	| LCHIJA | worleycaves                          | 1.3.0                  | worleycaves-1.3.0.jar                                    | None                                     |
	| LCHIJA | passableleaves                       | 2.0.0                  | PassableLeaves-1.12.2-2.0.0.jar                          | None                                     |
	| LCHIJA | coffeework                           | @version@              | CoffeeWorkshop_V1.2.1_MC1.12.2.jar                       | None                                     |
	| UD     | emoticons_core                       | 0.2.1                  | minecraft.jar                                            | None                                     |

	Loaded coremods (and transformers): 
GenderLoadingPlugin ([1.12.2]Gender-1.2.9.jar)
  com.github.ipixeli.gender.coremod.GenderClassTransformer
PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  teamrtg.passableleaves.asm.PassableLeavesTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.4.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
CreativePatchingLoader (CreativeCore_v1.9.37_mc1.12.2.jar)
  
EmoticonsCore (emoticons-0.2.1-1.12.2.jar)
  mchorse.emoticons.core.EmoCoreClassTransformer
HCASM (HammerCore-1.12.2-2.0.4.1.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 2624 names; 1121 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
Dependent Mods:
    -Improvable Skills (improvableskills) @3.6.0r

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['starwolf62'/2825, l='Copy of fwainf', x=-448.00, y=69.64, z=339.13]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Laike-Endaril** [comment]
Fixed in latest release!
