### ISSUE TITLE
Seemingly another vampirism conflict.

### ISSUE THREAD

**Issue by rfwainug** [Laike-Endaril/Dynamic-Stealth#21]
[redacted]

**Comment by rfwainug** [comment]
Sorry for this one, after temperarily taking out your mod I could see the world for what it was; A problem involving the server config having spawn protect configurations butting heads with FTBs' own spawn protect functionality lead to a cascading failure of infinitely generated cows until the server could take no more.

**Comment by Laike-Endaril** [comment]
@rfwainug The RAM used for all those cows may have been a major contributor to your other error, which I just wrote a lengthy explanation on and closed.  Probably worth reading at least part of, if you want a better idea of what was likely happening behind the scenes.
