### ISSUE TITLE
[Suggestion] Detection sound/meter

### ISSUE THREAD

**Issue by MerekiDor** [Laike-Endaril/Dynamic-Stealth#22]
Basically, there should be a small arrow around your crosshair (or anywhere else, really) that would flash whenever you are detected, and pointing in the direction the enemy that has spotted you or is about to spot. Basically, it would work like in Far Cry 3/Watch Dogs 2. So whenever you're detected, the arrow flashes in the direction the enemy is, and a sound effect plays. The arrow will stay as long as you're detected. As you're hiding, the arrow still would point on the enemy, but it would lose it's opacity as they're losing you. Once you have 100% detection level, the arrow disappears since it's almost impossible to hide anymore, and it becomes pointless by that time, too.

Why? Because sometimes when enemies approach you from behind, or you're sneaking through the forest with mobs all around you, you must know where the danger is, and whether some mob is about to spot you. So lets say there are 5 zombies in every direction, and you can't focus on every single one of them, right? This is where that arrow would help so much: if the enemy is about to detect the player, they would know that before it's too late to hide or walk away.

**Comment by Laike-Endaril** [comment]
I think this idea is doable in my system, code-wise.  I'll have to think more on the implementation and programming details for a while though, so don't expect it too soon.

**Comment by Laike-Endaril** [comment]
After going through this in my head many times, I think properly implementing it might require a significant change to the core system...

...I'm not entirely sure if this will ever see the light of day or not.  Only time will tell for sure, but for now at least, I'm putting it to the side (but keeping it in the issue tracker).

**Comment by Laike-Endaril** [comment]
I may end up adding a more simplified version of the idea; ie. skyrim style "eye" indicator.  I realize it's not exactly what you were going for, but it's *probably* the only thing I'll end up doing for this kind of feature...we'll see as time goes on

**Comment by Laike-Endaril** [comment]
Implemented in latest release (056), though not exactly in the way you described.  May see some improvements to this feature over time.
