### ISSUE TITLE
Crash on flee?

### ISSUE THREAD

**Issue by DcNdrew** [Laike-Endaril/Dynamic-Stealth#23]
I spotted an Ancient Warfare entity, I turned back in no time and started to run. Then crash. Dynamic Stealth was kinda the first entry in the crashlog.
https://paste.ee/p/ej8S6

**Comment by Laike-Endaril** [comment]
Thanks for the report!  Luckily this was due to a dumb mistake made while half asleep, so it was easy to fix.  I'll probably release a fixed version today, though I might try adding another small feature while I'm at it.

**Comment by Laike-Endaril** [comment]
This is now fixed in the most recent release (045)
