### ISSUE TITLE
Another crash, but I don't know why

### ISSUE THREAD

**Issue by DcNdrew** [Laike-Endaril/Dynamic-Stealth#25]
https://paste.ee/p/nLHTU

**Comment by Laike-Endaril** [comment]
I've posted a new version that should fix this (047).  If you can try it out in your pack and tell me whether it fixes the issue for sure, that would be great

**Comment by Laike-Endaril** [comment]
I'm going to assume this is fixed and that you haven't seen this thread, but if it's not fixed (or you find any other issues) feel free to open a new issue.
