### ISSUE TITLE
Compatibility with Custom NPCs

### ISSUE THREAD

**Issue by Cre8or** [Laike-Endaril/Dynamic-Stealth#26]
Hello! I'm using Dynamic Stealth (`DynamicStealth-1.12.2.046.jar`) alongside Doggy Talents (`DoggyTalents-1.14.2.381-universal`), and I noticed the following mod interaction issue. Like all other mobs, the Doggy Talents dogs will go into the "scanning" mode after killing a target, where they slowly turn and scan the horizon for further threats - which is fine for regular mobs, but rather undesirable in this case, as the dogs will no longer follow the player until their threat level drops back down to 0%.

Because I want the dog to immediately follow the player after killing its target, I decided to try and add it to the threat bypassing list. In this case, the dog will follow me fine, but now it is spinning like a beyblade at all times, which is rather distracting and... ugly looking. Even after setting a custom head turning value to that specific class, I was unable to stop the spinning madness. And since I love both mods, I'd hate to remove either one to "fix" this issue.

Side note, in a previous version (I think ~1-2 weeks ago), all mobs exhibited the spinning behaviour once I globally disabled the threat level, which is why I'm posting the issue here and not on the Doggy Talents page, as I suspect it might be linked to the threat system.

**Comment by Laike-Endaril** [comment]
I'll see if I can alter the behavior of owned entities in DS to make them work better for things like this

I've noticed the..."spin effect" occasionally while using certain mods alongside DS but had not gotten any reports about it, so have been concentrating on other things.  I'll try to figure that out as well (but will do the owned entities first as it's a better solution to your current issue)

**Comment by Cre8or** [comment]
Thanks for the reply, glad to hear I'm not the only one who's experienced that issue. It's not a massive issue (seeing as it's mostly aesthetics), so I'm not *too* bothered by it for now. Regardless, looking forward to your fix! 😃

**Comment by Laike-Endaril** [comment]
I started testing, but have not encountered the spinning issue with only DS and doggy talents installed (and dogs using threat bypass mode).  I'm thinking a third mod is indirectly affecting them as well.

I have one idea of what may possibly be going on and will attempt to fix it, but if you have the time, maybe you can confirm whether or not it happens for you with only DS and doggy talents active, and if that works correctly, maybe you can figure out which of the other mods is involved.

Hopefully I can fix this in a general manner regardless of what other mods are involved, but having the third mod on hand would be good for testing.

**Comment by Laike-Endaril** [comment]
Also, just in case, what mode were your dogs set to?

**Comment by Cre8or** [comment]
With only the two mods installed I can no longer reproduce the issue (just like you), so I am now trying to figure out which additional mod(s) are causing it. Hmm...

Oh, and the spinning occured in all modes.

**Comment by Cre8or** [comment]
I found the culprit: Custom NPCs (`CustomNPCs_1.12.2(30Jan19)`) seems to be doing it. The issue doesn't occur without Dynamic Stealth, so I'm guessing there's something going on between these two mods.

**Comment by Laike-Endaril** [comment]
Yep, in fact it was with CustomNPCs that I had slimes spinning around.  Thanks for filtering through them.  I'll get to work finding a solution.

**Comment by Cre8or** [comment]
No problem! Hoping it won't be too much hassle to fix it.

**Comment by Laike-Endaril** [comment]
I've just released a new version that fixes the spin, and should at least address *some* of the stuff with owned entities.  Try it out when you get a chance.

I'm closing this issue since it's official focus after the title change is the spinny thing, but if you find something doesn't work very well, feel free to post a new issue for it!

**Comment by Laike-Endaril** [comment]
Accidental reference!  I just referenced this issue instead of another issue, sorry for any confusion.
