### ISSUE TITLE
incompatibility with dissolution

### ISSUE THREAD

**Issue by lag42** [Laike-Endaril/Dynamic-Stealth#27]
possessing an entity using dissolution with dynamic stealth installed makes you appear as if you're still in soul mode even letting you fly and if you look down you can see what you've possessed
i've made an issue on dissolution's repository too: https://github.com/Ladysnake/Dissolution/issues/112

**Comment by Laike-Endaril** [comment]
I'll post any updates in the other thread, to keep all info in one place

**Comment by Laike-Endaril** [comment]
Huh...I think github auto-closes issues based on keywords.  Not sure I like that.  Main issue is solved in my indev version, but still working on some other related compat for dissolution

**Comment by Laike-Endaril** [comment]
@lag42 General compat with dissolution should be pretty good now.  Feel free to open a new issue if you notice anything other than the thing when player shells come into view and sometimes lag/don't have their skins; that's something on dissolution's side I need to bug Pyrofab about (will post in the other thread about it)

Oh right, and I released a new version with the fixes (049)
