### ISSUE TITLE
Possible incompatibility with Apotheosis.

### ISSUE THREAD

**Issue by rfwainug** [Laike-Endaril/Dynamic-Stealth#28]
net.minecraft.util.ReportedException: Ticking entityat net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.IllegalArgumentExceptionat net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18) ~[rs.class:?]at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37) ~[rs.class:?]at shadows.deadly.gen.BossFeature.generate(BossFeature.java:34) ~[BossFeature.class:?]at shadows.deadly.gen.WorldGenerator.run(WorldGenerator.java:38) ~[WorldGenerator.class:?]at shadows.deadly.gen.WorldGenerator.generate(WorldGenerator.java:29) ~[WorldGenerator.class:?]at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167) ~[GameRegistry.class:?]at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020) ~[axw.class:?]at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999) ~[axw.class:?]at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?]at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]at net.minecraft.world.ChunkCache.(ChunkCache.java:37) ~[and.class:?]at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:113) ~[ze.class:?]at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:51) ~[zd.class:?]at net.minecraft.pathfinding.PathNavigateGround.func_75494_a(SourceFile:73) ~[zd.class:?]at net.minecraft.entity.ai.EntityAIAttackMelee.func_75250_a(EntityAIAttackMelee.java:63) ~[xo.class:?]at com.fantasticsource.dynamicstealth.server.ai.NPEAttackTargetTaskHolder.func_75250_a(NPEAttackTargetTaskHolder.java:22) ~[NPEAttackTargetTaskHolder.class:?]at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94) ~[xf.class:?]at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) ~[vq.class:?]at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2356) ~[vp.class:?]at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?]at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) ~[vd.class:?]at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43) ~[zv.class:?]at net.minecraft.entity.passive.EntityWolf.func_70636_d(EntityWolf.java:212) ~[aam.class:?]at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2176) ~[vp.class:?]at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]at net.minecraft.entity.passive.EntityWolf.func_70071_h_(EntityWolf.java:230) ~[aam.class:?]at net.minecraft.world.World.func_72866_a(World.java:1993) ~[amu.class:?]at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]at net.minecraft.world.World.func_72870_g(World.java:1955) ~[amu.class:?]at net.minecraft.world.World.func_72939_s(World.java:1759) ~[amu.class:?]at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]

**Comment by rfwainug** [comment]
Hi again! :D

**Comment by Laike-Endaril** [comment]
Welcome back! XD (looking through stacktrace)

**Comment by Laike-Endaril** [comment]
Nope, this is all them.



Technical details:
There is an empty ArrayList that they expect not to be empty (named BOSS_ITEMS), which is getting passed into a vanilla function which crashes if you pass in an empty array, as seen in link below.

[https://github.com/Shadows-of-Fire/Apotheosis/blob/c5504b2e3623410ff0995fd1ef47341e7f1decf7/src/main/java/shadows/deadly/gen/BossFeature.java#L34](https://github.com/Shadows-of-Fire/Apotheosis/blob/c5504b2e3623410ff0995fd1ef47341e7f1decf7/src/main/java/shadows/deadly/gen/BossFeature.java#L34)

It is not checking whether it has been initialized before making the method call on that line, and apparently the generate() method can be called before the init() method.



Solution:
Go from this...
```java
	public static final List<BossItem> BOSS_ITEMS = new ArrayList<>();
```
...to this:
```java
	public static final List<BossItem> BOSS_ITEMS = new ArrayList<>();

	static
	{
		init();
	}
```


I'll post a link to this in the issue you posted on their tracker.  It's not the same error, but may be related, and the solution I included here may very well fix both.
