### ISSUE TITLE
Backstab broken?

### ISSUE THREAD

**Issue by DevTimur** [Laike-Endaril/Dynamic-Stealth#3]
I can not backstab anymore (Using backstab mod)
I think when you attack mob, it turn to you so fast, backstab even not getting registered.

**Comment by Laike-Endaril** [comment]
Thank you for the post!  I believe I've resolved this with a simple event priority change, to make sure my code executes AFTER backstab does its damage calculation.

The new version is already up for download

If you still notice issues on version 010, please let me know (by posting another issue), but I'm fairly certain it is working as intended now.
