### ISSUE TITLE
Mobs are invisible with Metamorph & Tiny Mob Farm

### ISSUE THREAD

**Issue by WenXin20** [Laike-Endaril/Dynamic-Stealth#33]
Forge v14.23.5.2810-1.12.2
Dynamic Stealth v1.12.2.055
[Tiny Mob Farm](https://minecraft.curseforge.com/projects/tiny-mob-farm) v1.0.4
[Metamorph](https://minecraft.curseforge.com/projects/metamorph) v1.1.7

When I place a mob into the mob farm blocks from Tiny Mob Farm mod, mobs appear invisible. 
Morphs acquired after killing a mob from Metamorph are also invisible. I don't know if this affects any other mod though. 
Mobs are visible again after removing Dynamic Stealth.

**Comment by Laike-Endaril** [comment]
I'll grab the mods and look into this.

**Comment by Laike-Endaril** [comment]
Woops, it may be fixed, but only in my indev version.  I like to leave issues open until they're fixed in a released version.

Anyway, if you want a temporary workaround in the meantime, you can set the minimum opacity to 1 (client settings -> entity fading)

**Comment by WenXin20** [comment]
Ok, thanks!

**Comment by Laike-Endaril** [comment]
Fixed in latest release! (056)
