### ISSUE TITLE
Primitive Mobs' Chameleon is colorless

### ISSUE THREAD

**Issue by WenXin20** [Laike-Endaril/Dynamic-Stealth#34]
Forge v14.23.5.2810-1.12.2
Dynamic Stealth v1.12.2.055
[Primitive Mobs](https://minecraft.curseforge.com/projects/primitive-mobs) v1.2.3a

Chameleons from Primitive Mobs are colorless instead of changing its color to match the block it is on top of. Removing Dynamic Stealth fixes this.

Colorless Chameleon:
![2019-03-02_19 39 33](https://user-images.githubusercontent.com/12000593/53689980-5cb69800-3d27-11e9-84af-cd50407bc971.png)

**Comment by Laike-Endaril** [comment]
Interesting, I'll look into it

**Comment by Laike-Endaril** [comment]
The next version has a general fix that fixes this issue for chameleons, grove sprites, and any other mob from any mod which uses blending colors

**Comment by WenXin20** [comment]
Ok, thanks!

**Comment by Laike-Endaril** [comment]
Fixed in latest release! (056)
