### ISSUE TITLE
DynamicStealth 056 + FantasticLib  002 crash the game by open a map

### ISSUE THREAD

**Issue by Titoo8899** [Laike-Endaril/Dynamic-Stealth#35]
Please fix this Problem.

Crash Report

The game crashed whilst exception ticking world
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.entity.ai.EntityAITasks.field_75779_e from class com.fantasticsource.dynamicstealth.common.DynamicStealth
-------------------------------------------------------------------------------------------------------------------
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.5-146.jar)
  CamPatchingLoader (1.12.2.minecamera-1.1.2.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.2.jar)
  FMLPlugin (albedo-0.1.3.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  EmoticonsCore (emoticons-0.2.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre126_mc1.12.2.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  CreativePatchingLoader (CreativeCore_v1.9.39_mc1.12.2.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  Snow! Real Magic! Core Mod (SnowRealMagic-0.3.1-coremod.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.0-alpha-9.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.19_mc1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  CamPatchingLoader (CMDCam+v1.4.2+mc1.12.2.jar)
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 3/7/19 6:59 PM
Description: Exception ticking world

java.lang.IllegalAccessError: tried to access field net.minecraft.entity.ai.EntityAITasks.field_75779_e from class com.fantasticsource.dynamicstealth.common.DynamicStealth
	at com.fantasticsource.dynamicstealth.common.DynamicStealth.entityJoin(DynamicStealth.java:560)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_165_DynamicStealth_entityJoin_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1206)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:160)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.fantasticsource.dynamicstealth.common.DynamicStealth.entityJoin(DynamicStealth.java:560)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_165_DynamicStealth_entityJoin_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1206)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:160)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)

-- Affected level --
Details:
	Level name: Test world 2 V2
	All players: 1 total; [EntityPlayerMP['Titoo8899'/26, l='Test world 2 V2', x=-559.50, y=4.00, z=742.50]]
	Chunk stats: ServerChunkCache: 319 Drop: 53
	Level seed: 9101165636193618230
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-557,4,740), Chunk: (at 3,0,4 in -35,46; contains blocks -560,0,736 to -545,255,751), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 35 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4549334112 bytes (4338 MB) / 12314476544 bytes (11744 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 211 mods loaded, 210 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                            | Version              | Source                                                               | Signature                                |
	|:--------- |:----------------------------- |:-------------------- |:-------------------------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                     | 1.12.2               | minecraft.jar                                                        | None                                     |
	| UCHIJAAAA | mcp                           | 9.42                 | minecraft.jar                                                        | None                                     |
	| UCHIJAAAA | FML                           | 8.0.99.99            | forge-1.12.2-14.23.5.2768.jar                                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                         | 14.23.5.2768         | forge-1.12.2-14.23.5.2768.jar                                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | MineCameraDummy               | 1.0.0                | minecraft.jar                                                        | None                                     |
	| UCHIJAAAA | creativecoredummy             | 1.0.0                | minecraft.jar                                                        | None                                     |
	| UCHIJAAAA | itemphysic                    | 1.4.0                | minecraft.jar                                                        | None                                     |
	| UCHIJAAAA | littletilescore               | 1.0.0                | minecraft.jar                                                        | None                                     |
	| UCHIJAAAA | smoothfontcore                | mc1.12.2-2.0-alpha-7 | minecraft.jar                                                        | None                                     |
	| UCHIJAAAA | obfuscate                     | 0.2.6                | minecraft.jar                                                        | None                                     |
	| UCHIJAAAA | clothesline-hooks             | 1.12.2-0.0.1.2       | minecraft.jar                                                        | None                                     |
	| UCHIJAAAA | dsurroundcore                 | 3.5.4.3              | minecraft.jar                                                        | None                                     |
	| UCHIJAAAA | albedocore                    | 0.1                  | minecraft.jar                                                        | None                                     |
	| UCHIJAAAA | smoothfont                    | mc1.12.2-2.0-alpha-9 | SmoothFont-mc1.12.2-2.0-alpha-9.jar                                  | None                                     |
	| UCHIJAAAA | minecamera                    | 1.1.1                | 1.12.2.minecamera-1.1.2.jar                                          | None                                     |
	| UCHIJAAAA | securitycraft                 | v1.8.12              | [1.12.2]+SecurityCraft+v1.8.12.jar                                   | None                                     |
	| UCHIJAAAA | versionchecker                | @VERSION@            | [1.12.2]+VersionChecker-1.4.0.jar                                    | None                                     |
	| UCHIJAAAA | fistful_of_hay                | 1.0.1                | a_fistful_of_hay-1.0.1.jar                                           | None                                     |
	| UCHIJAAAA | albedo                        | 0.1.3                | albedo-0.1.3.jar                                                     | None                                     |
	| UCHIJAAAA | applecore                     | 3.2.0                | AppleCore-mc1.12.2-3.2.0.jar                                         | None                                     |
	| UCHIJAAAA | arcademod                     | 2.1.5                | arcademod-2.1.5-1.12.2.jar                                           | None                                     |
	| UCHIJAAAA | archicraft                    | 1.5.0                | Archicraft-1.5.0.jar                                                 | None                                     |
	| UCHIJAAAA | architecturecraft             | @VERSION@            | ArchitectureCraft-ElytraDev-Mod-1.12.2.jar                           | None                                     |
	| UCHIJAAAA | jei                           | 4.15.0.268           | jei_1.12.2-4.15.0.268.jar                                            | None                                     |
	| UCHIJAAAA | quark                         | r1.5-146             | Quark-r1.5-146.jar                                                   | None                                     |
	| UCHIJAAAA | autoreglib                    | 1.3-26               | AutoRegLib-1.3-26.jar                                                | None                                     |
	| UCHIJAAAA | auto_third_person             | 1.2.0                | autothirdperson-1.2.0.jar                                            | None                                     |
	| UCHIJAAAA | basketcase                    | 1.0.29               | Basketcase-v1.0.29-mc1.12.2.jar                                      | None                                     |
	| UCHIJAAAA | betteranimals                 | 3.1                  | betteranimals-4.0.jar                                                | None                                     |
	| UCHIJAAAA | betteranimalsplus             | 5.0.1                | betteranimalsplus-5.0.1.jar                                          | None                                     |
	| UCHIJAAAA | mts                           | 13.0.0               | Minecraft+Transport+Simulator-1.12.2-13.0.0.jar                      | None                                     |
	| UCHIJAAAA | unuparts                      | 1.9.1                | UNU+Parts+Pack+[MTS]+1.10.2-13.0.0-1.9.1.jar                         | None                                     |
	| UCHIJAAAA | btcivil                       | 1.2.1                | BlackThorne+Civilian+Pack+[MTS]+1.10.2-11.2.0-1.3.0.jar              | None                                     |
	| UCHIJAAAA | blackthorne                   | 1.9.3                | BlackThorne+Empire+Vehicles+[MTS]+[IR]+1.10.2-13.0.0-1.5.0-1.9.3.jar | None                                     |
	| UCHIJAAAA | blockcraftery                 | 1.12.2-1.2.0         | blockcraftery-1.12.2-1.2.0.jar                                       | None                                     |
	| UCHIJAAAA | blur                          | 1.0.4-14             | Blur-1.0.4-14.jar                                                    | None                                     |
	| UCHIJAAAA | bookshelf                     | 2.3.577              | Bookshelf-1.12.2-2.3.577.jar                                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | zawa                          | 1.12.2-1.5.5         | zawa+-+1.5.5+(1.12.2).jar                                            | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| UCHIJAAAA | bookworm                      | 1.12.2-2.1.0         | bookworm+-+2.1.0+(1.12.2).jar                                        | None                                     |
	| UCHIJAAAA | forgelin                      | 1.8.2                | Forgelin-1.8.2.jar                                                   | None                                     |
	| UCHIJAAAA | bountiful                     | 2.2.0                | Bountiful-2.2.0.jar                                                  | None                                     |
	| UCHIJAAAA | carryon                       | 1.12.1               | CarryOn+MC1.12.2+v1.12.1.jar                                         | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| UCHIJAAAA | ctm                           | MC1.12.2-0.3.3.22    | CTM-MC1.12.2-0.3.3.22.jar                                            | None                                     |
	| UCHIJAAAA | chisel                        | MC1.12.2-0.2.1.35    | Chisel-MC1.12.2-0.2.1.35.jar                                         | None                                     |
	| UCHIJAAAA | cathedral                     | 1.12.2-1.9.7k        | Cathedral-1.12.2-1.9.7k.jar                                          | None                                     |
	| UCHIJAAAA | chineseworkshop               | 1.2.5                | ChineseWorkshop-1.12.2_1.2.5.jar                                     | None                                     |
	| UCHIJAAAA | chiselsandbits                | 14.30                | chiselsandbits-14.30.jar                                             | None                                     |
	| UCHIJAAAA | cleanview                     | 1.12.2-v1a           | CleanView-1.12.2-v1a.jar                                             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | cmdcam                        | 1.4.0                | CMDCam+v1.4.2+mc1.12.2.jar                                           | None                                     |
	| UCHIJAAAA | coloredredstone               | 1.3.1                | Colored+Redstone-1.3.1.jar                                           | None                                     |
	| UCHIJAAAA | colouredsealanterns           | 1.0                  | ColouredSeaLanterns-1.12.2-1.0.jar                                   | None                                     |
	| UCHIJAAAA | corpse                        | 1.12.2-1.0.0         | corpse-1.12.2-1.0.0.jar                                              | None                                     |
	| UCHIJAAAA | cosmeticbeds                  | 1.12.2-1.0.2.2       | cosmeticbeds-1.12.2-1.0.2.2.jar                                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAA | costumes                      | 2.0.0                | Costumes-1.12.2.jar                                                  | None                                     |
	| UCHIJAAAA | craipystutorialmod            | 1.0.1                | craipystutorialmod-1.12.2-1.1.0-open-alpha-SNAPSHOT.jar              | None                                     |
	| UCHIJAAAA | creativecore                  | 1.9.9                | CreativeCore_v1.9.39_mc1.12.2.jar                                    | None                                     |
	| UCHIJAAAA | creativefirework              | 1.0.1                | creativefirework-1.0.1.jar                                           | None                                     |
	| UCHIJAAAA | crypto                        | 1.1.0                | Crypto_1.12.2-1.1.0.jar                                              | None                                     |
	| UCHIJAAAA | dailyreward                   | 3                    | CustomDailyReward-r1.0-3.jar                                         | None                                     |
	| UCHIJAAAA | customnpcs                    | 1.12                 | CustomNPCs_1.12.2(30Jan19).jar                                       | None                                     |
	| UCHIJAAAA | dawnoftime                    | 0.1                  | dawnoftime-alpha-1.0.2.jar                                           | None                                     |
	| UCHIJAAAA | ptrmodellib                   | 1.0.3                | PTRLib-1.0.3.jar                                                     | None                                     |
	| UCHIJAAAA | props                         | 2.6.2                | Decocraft-2.6.2_1.12.2.jar                                           | None                                     |
	| UCHIJAAAA | df-roads                      | 1.5.2-mc1.12.2       | df-roads-1.5.2-mc1.12.2.jar                                          | None                                     |
	| UCHIJAAAA | dwtmtspack                    | 8.0.0                | DWTPack_V0.3[beta].jar                                               | None                                     |
	| UCHIJAAAA | fantasticlib                  | 1.12.2.002           | FantasticLib-1.12.2.002.jar                                          | None                                     |
	| UCHIJAAAA | dynamicstealth                | 1.12.2.056           | DynamicStealth-1.12.2.056.jar                                        | None                                     |
	| UCHIJAAAA | elevatorid                    | 1.4.0                | ElevatorMod-1.12.2-1.4.0.jar                                         | None                                     |
	| UCHIJAAAA | emoticons                     | 0.2.1                | emoticons-0.2.1-1.12.2.jar                                           | None                                     |
	| UCHIJAAAA | engineersdecor                | 1.0.1-b4             | engineersdecor-1.12.2-1.0.1-b4.jar                                   | ed58ed655893ced6280650866985abcae2bf7559 |
	| UCHIJAAAA | exocraft                      | 1.1.0                | ExoCraft-1.12.x-(v.1.1.0).jar                                        | None                                     |
	| UCHIJAAAA | fairylights                   | 2.1.5                | fairylights-2.1.5-1.12.2.jar                                         | None                                     |
	| UCHIJAAAA | faunaandecology               | 0.1.2.7              | FE-1.12.2-0.1.2.7.jar                                                | None                                     |
	| UCHIJAAAA | ferdinandsflowers             | 1.10.4.1             | Ferdinand's+Flowers-1.12.x-1.10.4.1.jar                              | None                                     |
	| UCHIJAAAA | fcl                           | 1.XII.45             | Fexcraft+Common+Library-1.XII.45.jar                                 | None                                     |
	| UCHIJAAAA | tmt                           | 1.1                  | Fexcraft+Common+Library-1.XII.45.jar                                 | None                                     |
	| UCHIJAAAA | foamflower                    | 1.12.2-1.0.0.0-beta1 | foamflower-1.12.2-1.0.0.0-beta1.jar                                  | None                                     |
	| UCHIJAAAA | freelook                      | 1.2.2                | FreeLook-1.2.2.jar                                                   | None                                     |
	| UCHIJAAAA | furenikusroads                | 1.0.1                | Fureniku's+Roads-1.0.1.jar                                           | None                                     |
	| UCHIJAAAA | cfm                           | 6.2.0                | furniture-6.2.0-1.12.2.jar                                           | None                                     |
	| UCHIJAAAA | futureminecraf                | 1.2                  | FutureVersionsV1.2.0.1.jar                                           | None                                     |
	| UCHIJAAAA | trackapi                      | 1.1                  | TrackAPI-1.1_1.12.jar                                                | None                                     |
	| UCHIJAAAA | fvtm                          | 2.9.35               | FVTM-2.9.35-1.12.x.jar                                               | None                                     |
	| UCHIJAAAA | globalgamerules               | 2.2                  | GlobalGameRules-1.12.2-2.2.7.jar                                     | None                                     |
	| UCHIJAAAA | gnomed                        | 1.0.0                | Gnomed-1.0.jar                                                       | None                                     |
	| UCHIJAAAA | gokistats                     | @version@            | gokiStats-1.2.5.1.jar                                                | None                                     |
	| UCHIJAAAA | growthcraft                   | 4.0.4.400            | growthcraft-1.12.2-4.0.4.400.jar                                     | None                                     |
	| UCHIJAAAA | growthcraft_apples            | 4.0.4.400            | growthcraft-1.12.2-4.0.4.400.jar                                     | None                                     |
	| UCHIJAAAA | growthcraft_bamboo            | 4.0.4.400            | growthcraft-1.12.2-4.0.4.400.jar                                     | None                                     |
	| UCHIJAAAA | growthcraft_cellar            | 4.0.4.400            | growthcraft-1.12.2-4.0.4.400.jar                                     | None                                     |
	| UCHIJAAAA | growthcraft_bees              | 4.0.4.400            | growthcraft-1.12.2-4.0.4.400.jar                                     | None                                     |
	| UCHIJAAAA | growthcraft_fishtrap          | 4.0.4.400            | growthcraft-1.12.2-4.0.4.400.jar                                     | None                                     |
	| UCHIJAAAA | growthcraft_grapes            | 4.0.4.400            | growthcraft-1.12.2-4.0.4.400.jar                                     | None                                     |
	| UCHIJAAAA | growthcraft_hops              | 4.0.4.400            | growthcraft-1.12.2-4.0.4.400.jar                                     | None                                     |
	| UCHIJAAAA | growthcraft_milk              | 4.0.4.400            | growthcraft-1.12.2-4.0.4.400.jar                                     | None                                     |
	| UCHIJAAAA | growthcraft_rice              | 4.0.4.400            | growthcraft-1.12.2-4.0.4.400.jar                                     | None                                     |
	| UCHIJAAAA | cgm                           | 0.9.2                | guns-0.9.2-1.12.2.jar                                                | None                                     |
	| UCHIJAAAA | gymcraft                      | 1.0.0                | GymCraft+for+Minecraft+1.12.2.jar                                    | None                                     |
	| UCHIJAAAA | hammercore                    | 2.0.4.2              | HammerCore-1.12.2-2.0.4.2.jar                                        | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAA | heroicarmory                  | 1.1.3                | heroicarmory-1.2.0.jar                                               | None                                     |
	| UCHIJAAAA | hospital_mod__facilities_pack | 1.12.2               | hospital-mod-facilities-pack-1-12-2-V1.zip                           | None                                     |
	| UCHIJAAAA | hospitalmodtheatrepackalphav1 | Alpha V1             | Hospital_Mod_Theatre_Pack_AlphaV1.zip                                | None                                     |
	| UCHIJAAAA | ichunutil                     | 7.2.0                | iChunUtil-1.12.2-7.2.0.jar                                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| UCHIJAAAA | imaginary                     | 1.0.3                | imaginary-1.0.3-1.12.jar                                             | None                                     |
	| UCHIJAAAA | immersiveengineering          | 0.12-89              | ImmersiveEngineering-0.12-89.jar                                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | immersiveposts                | 0.0.5                | ImmersivePosts-0.0.5.jar                                             | 0ba25d8c0ec23537afc6db926e1ea764335a33b1 |
	| UCHIJAAAA | immersiverailroading          | 1.5.0                | ImmersiveRailroading-1.5.0_1.12.jar                                  | None                                     |
	| UCHIJAAAA | improvableskills              | 3.6.1r               | ImprovableSkills-1.12.2-3.6.1r.jar                                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAA | ic2                           | 2.8.111-ex112        | industrialcraft-2-2.8.111-ex112.jar                                  | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | industrialrenewal             | 0.8.1                | IndustrialRenewal_1.12.2-0.8.1.jar                                   | None                                     |
	| UCHIJAAAA | itemzoom                      | 1.11                 | itemzoom_1.12.2-1.11.jar                                             | None                                     |
	| UCHIJAAAA | joes_superheroes_mod          | 1.4.0                | Joe's Superheroes Mod V 1.4.1 - 1.12.2.jar                           | None                                     |
	| UCHIJAAAA | jph                           | 1.0                  | jph_1.12-1.0.jar                                                     | None                                     |
	| UCHIJAAAA | jaff                          | 1.7_for_1.12         | JustAFewFish-1.7_for_1.12.jar                                        | None                                     |
	| UCHIJAAAA | buildingblocks                | 1.2                  | JustBuildIt+MC1.12.2+v1.2.jar                                        | None                                     |
	| UCHIJAAAA | jeid                          | 1.0.2-26             | JustEnoughIDs-1.0.2-26.jar                                           | None                                     |
	| UCHIJAAAA | landlust                      | 1.12.2-0.3.6         | landlust-1.12.2-0.3.6.jar                                            | None                                     |
	| UCHIJAAAA | lilcritters                   | 1.12.2-0.0.1.3-beta4 | lilcritters-1.12.2-0.0.1.3-beta4.jar                                 | None                                     |
	| UCHIJAAAA | limelib                       | 1.7.12               | limelib-1.12.2-1.7.12.jar                                            | None                                     |
	| UCHIJAAAA | littletiles                   | 1.5.0                | LittleTiles_v1.5.0-pre126_mc1.12.2.jar                               | None                                     |
	| UCHIJAAAA | locks                         | 2.2.1                | Locks-2.2.1.jar                                                      | None                                     |
	| UCHIJAAAA | lumpi                         | 0.7                  | lumpi-1.12-0.7.jar                                                   | None                                     |
	| UCHIJAAAA | malisiscore                   | 1.12.2-6.4.0         | malisiscore-1.12.2-6.4.0.jar                                         | None                                     |
	| UCHIJAAAA | malisisdoors                  | 1.12.2-7.3.0         | malisisdoors-1.12.2-7.3.0.jar                                        | None                                     |
	| UCHIJAAAA | mcpaint                       | 1.2.4                | mcpaint-1.2.4.jar                                                    | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| UCHIJAAAA | melvinssignpack               | 1.0.0                | Melvins_Simple_Sign_Pack-Beta-0.0.4.jar                              | None                                     |
	| UCHIJAAAA | mm                            | 1.2                  | MerchMod-1.2.jar                                                     | None                                     |
	| UCHIJAAAA | minewatch                     | 3.13                 | Minewatch-1.12.X-3.13.jar                                            | None                                     |
	| UCHIJAAAA | mirageorb                     | 1.1.0                | mirageorb-1.12.2-1.1.0.jar                                           | None                                     |
	| UCHIJAAAA | mmmpack                       | 0.0.0                | mmmpack V.1 Beta.jar                                                 | None                                     |
	| UCHIJAAAA | mocostumes                    | 0.0.1                | Mo' Costumes -1.12.2 0.0.1.jar                                       | None                                     |
	| UCHIJAAAA | mobarmormod                   | 1.0.3b               | Mob+Armor+Mod+V1.0.3b-1.12.2.jar                                     | None                                     |
	| UCHIJAAAA | modernlamps                   | 1.0.3                | ModernLights-1.0.3_1.12.jar                                          | None                                     |
	| UCHIJAAAA | tm                            | 1.0 - MC 1.12        | mOREs+Mod+1.0.2_beta.jar                                             | None                                     |
	| UCHIJAAAA | moreswordonline               | 2.8.2                | MoreSwordOnline+v2.8.1+-+1.12.2.jar                                  | None                                     |
	| UCHIJAAAA | mrcrayfishvehiclespawner      | 1.3                  | Mr_Crayfish_Vehicle_Spawner_1.3.jar                                  | None                                     |
	| UCHIJAAAA | mtsseagullcivilpack           | 2.0.0                | MTS+Seagull's+civil+pack+1.12.0.jar                                  | None                                     |
	| UCHIJAAAA | mtsseagullmilitarypack        | 1.4.0                | MTS+Seagull's+military+pack+1.4.3.jar                                | None                                     |
	| UCHIJAAAA | mtsseagulltrinpartpack        | 1.0.0                | MTS+seagull's+trin+parts+pack+1.5.0.jar                              | None                                     |
	| UCHIJAAAA | mtsofficialpack               | 9.0.0                | MTS_Official_Pack_V09.jar                                            | None                                     |
	| UCHIJAAAA | blueboyscaterpillarmtspack    | 1.1.0                | MTS_Caterpillar_Pack_V1.1.1.jar                                      | None                                     |
	| UCHIJAAAA | mw                            | 1.11.7.7             | mw-1.11.7.7_mc1.12.2.jar                                             | None                                     |
	| UCHIJAAAA | namenax                       | 1.0.0                | Namenax-1.0.0-mc1.12.2.jar                                           | None                                     |
	| UCHIJAAAA | faunanatural                  | 1.12.2-1.3.2         | NaturalFauna+Mod-1.12.2-1.3.2.jar                                    | None                                     |
	| UCHIJAAAA | currency                      | 3.1.5                | NeverEnoughCurrency-4.0.1.jar                                        | None                                     |
	| UCHIJAAAA | ngtlib                        | 2.4.3                | NGTLib2.4.3-20_forge-1.12.2-14.23.2.2611.jar                         | None                                     |
	| UCHIJAAAA | noctrl                        | 1.2                  | noctrl-1.2.jar                                                       | None                                     |
	| UCHIJAAAA | noel                          | 1.0                  | noel-1.12.2-1.0.2.jar                                                | None                                     |
	| UCHIJAAAA | notenoughroofs                | 0.8.0.0              | notenoughroofs-1.12.2-0.8.0.0.jar                                    | None                                     |
	| UCHIJAAAA | onepiececraft                 | 2.2.1                | onepiececraft-2.2.

**Comment by Laike-Endaril** [comment]
Thanks for the report.  I should be able to release a fixed version today.

**Comment by Laike-Endaril** [comment]
Fixed in latest release (057)
