### ISSUE TITLE
EvilCraft Vengeance Spirit crashes game

### ISSUE THREAD

**Issue by BlockTheVillager** [Laike-Endaril/Dynamic-Stealth#36]
[latest.log](https://github.com/Laike-Endaril/Dynamic-Stealth/files/2943435/latest.log)
My game crashes everytime it has to render a vengeance spirit, it has to do with fantasticsource.mctools at the very least.

**Comment by Laike-Endaril** [comment]
Thanks for the log file, I'll start looking into it

**Comment by Laike-Endaril** [comment]
This is now fixed in the latest version (058)
