### ISSUE TITLE
[Bug] 3d model weapon in other mod has missing the texture

### ISSUE THREAD

**Issue by MokoBlack** [Laike-Endaril/Dynamic-Stealth#38]
When installed  DS

**Comment by MokoBlack** [comment]
Not on all mod , such as Kaishi's Weapons and ForgeCraft

**Comment by Laike-Endaril** [comment]
For Kaishi's Weapons, I got missing resources with only Kaishi's Weapons installed.

ForgeCraft is not even running for me (crashes with no other mods installed except its dependency).

If you have ForgeCraft running alongside DS, try removing DS and see if ForgeCraft still has missing textures in the log or not.  If so, send me the log file and I can look into it further.

**Comment by MokoBlack** [comment]
To run Forgcraft need CraftTweaker . and yes , also missing resources

**Comment by Laike-Endaril** [comment]
Alright, ForgeCraft is now running, but I'm not seeing any issues in-game.  The log throws a ton of errors for everything besides DS, but as far as actual gameplay goes, I haven't seen any missing textures with DS, ForgeCraft, and Kaishi's Weapons installed.

I need...

1. A log file!  It contains a list of all your mods and their versions, your forge version, and tons of other info I don't want to ask a lot of questions to get.

2. Exact details; which textures are missing for what items?

**Comment by MokoBlack** [comment]
Just the weapon ，other thing is usual 
How can i got the log? is that?
[2019-03-16-4.log.gz](https://github.com/Laike-Endaril/Dynamic-Stealth/files/2974923/2019-03-16-4.log.gz)

**Comment by Laike-Endaril** [comment]
Yep, that's the file.

When you say "the weapon", what exactly do you mean?  A certain weapon from a certain mod?

Which weapon?

**Comment by MokoBlack** [comment]
Oh sorry , is all 3D-model weapons in Kaishi'weapons

**Comment by Laike-Endaril** [comment]
Ah, I just noticed you're using Dynamic Stealth 1.12.2.051

This is an old version of the mod which has a bug that is already fixed in newer versions, in fact it was fixed in 1.12.2.052

Please update to a newer version for the fix!


Oh, but if you notice any problems with the newest version, feel free to open a new issue!
