### ISSUE TITLE
Crash my server

### ISSUE THREAD

**Issue by SeagalKru** [Laike-Endaril/Dynamic-Stealth#39]
[crash-2019-03-25_11.53.10-server.txt](https://github.com/Laike-Endaril/Dynamic-Stealth/files/3002339/crash-2019-03-25_11.53.10-server.txt)

**Comment by Laike-Endaril** [comment]
Thanks for the report!

This one is a confirmed bug in TickDynamic, and does not have anything to do with Dynamic Stealth itself.

I see you already made a post on their tracker as well.  Here are some extra details in another issue, if you're interested:
[https://github.com/The-Fireplace-Minecraft-Mods/TickDynamic/issues/30](https://github.com/The-Fireplace-Minecraft-Mods/TickDynamic/issues/30)
