### ISSUE TITLE
Red error message (no crash) (something about your mod potions)

### ISSUE THREAD

**Issue by Finelarme9** [Laike-Endaril/Dynamic-Stealth#41]
Hello
 Thank you for your mod! I liked to have a lot of possible configurations. This message to notice that I also receive this "red error message" (no crash) each time I start my server =>
` [06:37:13]: [INFO] [STDERR]: [com.fantasticsource.mctools.potions.Potions:parsePotion:91] ResourceLocation for potion "dynamicstealth:soulsight.60" not found!`
 Thank you for your feedback.
Ben

**Comment by Laike-Endaril** [comment]
Hey, thanks for the report.  Do you have the soul sight potion disabled in the configs for DS by chance?

If not, could you post a logfile for me to look through?

**Comment by Finelarme9** [comment]
Hello there

I didn't touch the potion config I guess : 

```
B:"Blindness Potion Recipes"=true
B:"Blindness Potions"=true
B:"Glowing Potion Recipes"=true
B:"Glowing Potions"=true
B:"Soul Sight Potion Recipes"=true
B:"Soul Sight Potions"=true
```
 I will post you the logfile in a few hours. Thank you man.

NB : I have 138 mods/Forge 2768/version 1.12.2.

**Comment by Laike-Endaril** [comment]
Well, you shouldn't be getting any conflict from your DS config settings or forge version...I'll look at the log when you have one available and see if I can figure out what's up

**Comment by Finelarme9** [comment]
Here is the file debug.log and latest.log. There is a lot of lines (138 mods) but you will find the error  message.
`[INFO] [STDERR]: [com.fantasticsource.mctools.potions.Potions:parsePotion:91] ResourceLocation for potion "dynamicstealth:soulsight.60" not found!`

[debug.log](https://github.com/Laike-Endaril/Dynamic-Stealth/files/3026119/debug.log)
[latest.log](https://github.com/Laike-Endaril/Dynamic-Stealth/files/3026120/latest.log)

I notice here again that there isn't crash, everything is working fine. But I don't understand why I have this "red message" in logs (each time i start my server).

Thank you in advance!

**Comment by Laike-Endaril** [comment]
Thanks again, I think I've found the issue; I screwed up some initialization code when fixing a *different* issue a little while back.  This does have some effect on gameplay, but not if you don't know what to look for; eg. the potion effects for assassinations would not have triggered if you assassinated something.

I should have a fix soon

**Comment by Laike-Endaril** [comment]
I've released a new version (066) which should fix this issue

If you get a chance to test it, please tell me what happens!

**Comment by Finelarme9** [comment]
Wow you are super fast man. Ok I will check that today and will give you some feedback. Thanks again.

**Comment by Finelarme9** [comment]
Alright. It worked, no more message in the console! A simple "new point", is there a way (with config file maybe) to not show the "threat HUD" for all hostile/agressive entities all the time like on my screenshot. In your previous mod version I  was seeing the "threat HUD" when mobs was attacking only (it is what I want).

![2019-03-31_12 45 45](https://user-images.githubusercontent.com/49093069/55288187-0c793700-53b4-11e9-9583-25dc86850745.png)

**Comment by Laike-Endaril** [comment]
Yes, I believe what you want is (client settings -> HUD -> targeting filter)
In that section of the config, you can enable/disable the targeting HUD based on mobs' current state.

Also, since you already have another mod for HP, you can disable the HP readout of the mob if you want to in (client settings -> HUD -> targeting HUD style -> components)

I'm going to close this issue since it's been resolved, but feel free to post any new issues you find, or if you have questions, those are better off in the comments on the forge page

Happy hunting o/
