### ISSUE TITLE
Request: Toggle stealth functionality for Players

### ISSUE THREAD

**Issue by edenhack** [Laike-Endaril/Dynamic-Stealth#43]
Um, how to describe this exactly. Is there a functional way to make it to where players are not in "stealth" toward each other? Such as one player sees another regardless of distance, light, basically all of your elements. It is just a bit of an inconvenience in some cases especially since it removes the individual from journeymap.

**Comment by Laike-Endaril** [comment]
Not in the current version, but this is a solid idea, and I have a "tracking" system already programmed but just not used for anything yet, which could be adapted to do this kind of thing.  I'll add this to my TODO list.

**Comment by edenhack** [comment]
I see that would be a great addition. Currently I've had to sadly turn off player senses to achieve my goal, which sucks cause not seeing mobs in the dark and stuff is really scary and adds to the ambiance of cave diving a lot!

**Comment by Laike-Endaril** [comment]
Yeah, I really enjoy spelunking with DS + Lycanite + Worley.  My day job has picked up again this week so I've been less active, but hopefully I'll put out an update this weekend with this feature...provided I don't end up working during the weekend as well.

**Comment by Laike-Endaril** [comment]
@edenhack I'm currently thinking of accomplishing this using a command-based system with server-side preference storage.

Basically something like
/dstealth hidefrom <playername> [<true/false>]

Entering a playername with no args shows whether you're hiding from them or not

Adding true on the end makes you hide from them (ie. default behavior if player senses is enabled)

Adding false allows them to "see" you, completely ignoring sight check (including LOS; this will also allow them to see you on their map mod, if it shows players)


Tell me what you think if you see this (and anyone else who reads, feel free to give your opinion)

**Comment by edenhack** [comment]
Yeah this sounds like a good system for teams. In general team functions are already performed by FTB Utilities so I see no reason to set up anything past what you are looking at doing for allowing players to show or hide for others. I don't know if it's possible, but maybe in the future if you can hook onto FTB Utilities and pull the teams parameters maybe you can make this co-work with FTB to ease the process of showing or hiding to a player. IE your team members in FTB can see you just fine, but opposing factions or other teams cannot. Then you could avoid individuals needing to enter an argument.

This suggestion is based mainly on optional dependency. I don't mean for you to 100% rely on FTB teams, but give the functionality simplification if the mod is included. It's usually a staple mod for servers to begin with because of the built in functions it has so I don't think this would do you more harm than good finding some way to hook into their system on a optional dependency basis.

**Comment by edenhack** [comment]
Yeah this sounds like a good system for teams. In general team functions are already performed by FTB Utilities so I see no reason to set up anything past what you are looking at doing for allowing players to show or hide for others. I don't know if it's possible, but maybe in the future if you can hook onto FTB Utilities and pull the teams parameters maybe you can make this co-work with FTB to ease the process of showing or hiding to a player. IE your team members in FTB can see you just fine, but opposing factions or other teams cannot. Then you could avoid individuals needing to enter an argument.

**Comment by Laike-Endaril** [comment]
Sounds good, I'll have to go look at their API or source.

I'll go with this general line of thought then (command-based with support for FTB and/or vanilla teams).
Maybe I'll use what I already mentioned as the base functionality, then add another similar command for FTB teams, with the individual filter (the first one) overriding the team filter, if an entry exists for a specific player

**Comment by edenhack** [comment]
I think that's a solid decision. In the end its up to you of course. If it's not worth the effort to incorporate ftb teams then your method alone is good functionally by itself. Sent from my Sprint Samsung Galaxy Note9.
-------- Original message --------From: Laike-Endaril <notifications@github.com> Date: 4/13/19  11:31 AM  (GMT-06:00) To: Laike-Endaril/Dynamic-Stealth <Dynamic-Stealth@noreply.github.com> Cc: Eden Hack <nathancbright@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [Laike-Endaril/Dynamic-Stealth] Request: Toggle stealth functionality for Players (#43) Sounds good, I'll have to go look at their API or source.
I'll go with this general line of thought then (command-based with support for FTB and/or vanilla teams).
Maybe I'll use what I already mentioned as the base functionality, then add another similar command for FTB teams, with the individual filter (the first one) overriding the team filter, if an entry exists for a specific player

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Laike-Endaril/Dynamic-Stealth","title":"Laike-Endaril/Dynamic-Stealth","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Laike-Endaril/Dynamic-Stealth"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Laike-Endaril in #43: Sounds good, I'll have to go look at their API or source.\r\n\r\nI'll go with this general line of thought then (command-based with support for FTB and/or vanilla teams).\r\nMaybe I'll use what I already mentioned as the base functionality, then add another similar command for FTB teams, with the individual filter (the first one) overriding the team filter, if an entry exists for a specific player"}],"action":{"name":"View Issue","url":"https://github.com/Laike-Endaril/Dynamic-Stealth/issues/43#issuecomment-482833131"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Laike-Endaril/Dynamic-Stealth/issues/43#issuecomment-482833131",
"url": "https://github.com/Laike-Endaril/Dynamic-Stealth/issues/43#issuecomment-482833131",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Laike-Endaril** [comment]
This is now available in the latest release (068).

I did not do any team support due to...complications...(on several levels)

**Comment by edenhack** [comment]
Haha of course, i figured it would be complicated but it was a thought for
possible functionality as a whole. Thank you for all your efforts.

**Comment by Laike-Endaril** [comment]
Apparently long ago when I added the command, I did not have the permissions set correctly.  This has been fixed in the latest release.

The general mod command is /dstealth

The subcommands are...
/dstealth hidefrom
Shows a list of all players you're *not* trying to hide from

/dstealth hidefrom <playername>
Tells you whether you're trying to hide from the player (default true)

/dstealth hidefrom <playername> <t/f/true/false>
Sets whether you're trying to hide from the player or not
