### ISSUE TITLE
More of a question than anything but...

### ISSUE THREAD

**Issue by Sunconure11** [Laike-Endaril/Dynamic-Stealth#45]
How does one disable the glow around hostiles/neutral mobs? I'd like to do so in my pack.

**Comment by Laike-Endaril** [comment]
(client settings -> HUD -> targeting HUD style -> glow)

This seems pretty likely to be the solution you're looking for, so I'm going to close this, but if you have any other questions, feel free to ask them on the forge page (https://minecraft.curseforge.com/projects/dynamic-stealth).

Ofc, if you find an error/crash/bug, or have a feature request, feel free to create a new issue on this tracker
