### ISSUE TITLE
NPE with latest build causing a server-ended crash

### ISSUE THREAD

**Issue by Sunconure11** [Laike-Endaril/Dynamic-Stealth#46]
https://pastebin.com/Rz8SJLKw

**Comment by Sunconure11** [comment]
@Laike-Endaril

**Comment by Laike-Endaril** [comment]
Thanks for the report!  The latest version (070) fixes this issue

**Comment by Sunconure11** [comment]
I think this may have resurfaced.

https://pastebin.com/y7EAfBuj

**Comment by Laike-Endaril** [comment]
The crash report you linked is still on an old version of DS (069)

You just need to grab version 070 or higher
