### ISSUE TITLE
And me again! Single - plays, the server - crash !!!

### ISSUE THREAD

**Issue by SeagalKru** [Laike-Endaril/Dynamic-Stealth#47]
[crash-2019-04-25_17.20.40-server.txt](https://github.com/Laike-Endaril/Dynamic-Stealth/files/3117346/crash-2019-04-25_17.20.40-server.txt)
[debug.log](https://github.com/Laike-Endaril/Dynamic-Stealth/files/3117347/debug.log)
[latest.log](https://github.com/Laike-Endaril/Dynamic-Stealth/files/3117348/latest.log)
[server.log](https://github.com/Laike-Endaril/Dynamic-Stealth/files/3117350/server.log)

**Comment by Laike-Endaril** [comment]
Thanks for the report!  The latest version (070) fixes this issue
