### ISSUE TITLE
Weapon specific attack potion effect bug

### ISSUE THREAD

**Issue by DevTimur** [Laike-Endaril/Dynamic-Stealth#49]
If you want to set certain weapon to cause potion effect when attacking. You as a Modpack maker have to select BOTH Attacker and Victim potion effects, or it will just not work.

In default options you left example of Ink sak => blindness, and glowstone => Glowing scripts.
they both not work. Untill you add attacker potion effect aswell.

**Comment by Laike-Endaril** [comment]
Confirmed, looking into it

**Comment by Laike-Endaril** [comment]
This should now be fixed in the latest release (071)
