### ISSUE TITLE
Guardian causing NPE?

### ISSUE THREAD

**Issue by Snownee** [Laike-Endaril/Dynamic-Stealth#5]
https://paste.dimdev.org/ewaricopim.mccrash
https://paste.dimdev.org/inibavodub.mccrash

**Comment by Laike-Endaril** [comment]
Thanks for the report!  I think I've tracked down the issue and should hopefully have a fix in the next release (version 014).  I'll leave this open for now and tell you when I think a released version should have a fix (hopefully within 24 hours)

**Comment by Laike-Endaril** [comment]
Should be fixed in the latest version, which is now available on curseforge
