### ISSUE TITLE
Log spam "camo = 0b"

### ISSUE THREAD

**Issue by DevTimur** [Laike-Endaril/Dynamic-Stealth#52]
[com.fantasticsource.dynamicstealth.server.senses.sight.Sight:visualStealthLevelInternal:384]: camo = 0b
[com.fantasticsource.dynamicstealth.server.senses.sight.Sight:visualStealthLevelInternal:384]: camo = 0b
[com.fantasticsource.dynamicstealth.server.senses.sight.Sight:visualStealthLevelInternal:384]: camo = 0b
[com.fantasticsource.dynamicstealth.server.senses.sight.Sight:visualStealthLevelInternal:384]: camo = 0b
[com.fantasticsource.dynamicstealth.server.senses.sight.Sight:visualStealthLevelInternal:384]: camo = 0b
[com.fantasticsource.dynamicstealth.server.senses.sight.Sight:visualStealthLevelInternal:384]: camo = 0b
[com.fantasticsource.dynamicstealth.server.senses.sight.Sight:visualStealthLevelInternal:384]: camo = 0b

In log window since version DynamicStealth-1.12.2.074

**Comment by Laike-Endaril** [comment]
Woops, had some debug messages left in from the armor penalty rework.  I'll fix this shortly.  Thanks for the report!

**Comment by Laike-Endaril** [comment]
This is now fixed in the latest release (1.12.2.076)
