### ISSUE TITLE
config text needs fixed

### ISSUE THREAD

**Issue by 0xebjc** [Laike-Endaril/Dynamic-Stealth#59]
Under the in game config under -> Client Settings -> HUD -> Target HUD Style
There are two settings with the same description "Text Opacity".  I believe the first one should be labeled "Reticle Opacity"

This may have been intentional, but for me it was not apparent and confusing.  I only found which one manipulated the reticle by trial and error.
-jc

**Comment by Laike-Endaril** [comment]
Good catch

**Comment by Laike-Endaril** [comment]
This should now be fixed in the latest release
