### ISSUE TITLE
Crashes when spotted by a Blaze or Wither Skeleton

### ISSUE THREAD

**Issue by Syampuuh** [Laike-Endaril/Dynamic-Stealth#6]
Blaze crash log:
https://pastebin.com/DMQ0dECA

Skeleton crash log:
https://pastebin.com/Jwzk3V6K

This seems to happen most consistently after attacking them from stealth with a projectile, sometimes immediately on their death and sometimes only once they've become hostile. Seems to be something related to how they're trying to retaliate, but I'm sure no expert.

**Comment by Laike-Endaril** [comment]
Thanks for the report, I will hopefully have a fix out sometime tonight

**Comment by Laike-Endaril** [comment]
Should now be fixed in the latest version!  Please tell me if you find any other issues! (or the same issue, though that should not happen)
