### ISSUE TITLE
[Bug?] Animania mobs are weird when attacked

### ISSUE THREAD

**Issue by CactusDuud** [Laike-Endaril/Dynamic-Stealth#60]
Animania AIs work in a sort of weird way, so I'm not really sure if this is a bug or not, but when certain mobs (like the stallion) are attacked, they'll become "aggressive" despite being unable to do damage. It's not really a major bug, but it is somewhat annoying if I accidentally hit something and trigger the targeting UI.

**Comment by Laike-Endaril** [comment]
Dynamic stealth attempts to automatically categorize mobs as passive or non-passive based on a few factors, including their "attack damage".  Ie. the stallion must have attack damage of more than 0, which might cause some other mod incompatibilities for Animania as well, but...

...luckily I have a thing for this.  (server settings -> threat system -> entity specific -> passiveness)
If you need to find the entity ID of the mob, you can look at the entity reference file in...
main modpack folder/config/fantasticlib/reference/entities.txt

If you know your way around Animania and what should be passive or non-passive, and end up going through that setting for them, maybe send me your config and I can add default settings for them in there

**Comment by Laike-Endaril** [comment]
Nvm, got it figured out, though they had a lot of animals for me to go through :/

**Comment by Laike-Endaril** [comment]
This should now be fixed in the latest release (if you use the new default settings for passiveness)
