### ISSUE TITLE
Ancient Warfare 2 compat

### ISSUE THREAD

**Issue by ILLOMIURGE** [Laike-Endaril/Dynamic-Stealth#63]
Well, AW NPC's are not responding to commands due to this mod's AI changes. Nothing less, nothing more.

**Comment by Laike-Endaril** [comment]
Haven't gotten around to this one yet; just responding so you know I'm aware of it, at least.

Not sure when I'll get to look into it properly yet (it might be one of the more complex AI compat issues, so I've been putting it off a bit)

Edit: Will try to look into this one after the Minecolonies issue (may take some time)

**Comment by Laike-Endaril** [comment]
I briefly tested with only Ancient Warfare 2 and its requirements, and then with Dynamic Stealth (and its requirements) installed, and all the same commands seemed to do all the same things as with only Ancient Warfare 2 installed.

Ie...
Set home (V): sets the NPC's home, and they move to it
Clear home: doesn't seem to work (even without DS installed)
Attack/Move (X): they move to the spot, then move back to their home position (and probably attack stuff, if there's anything to attack)
Guard (C): they follow the target entity (and probably guard it)
Set upkeep: changes the symbol above their head to NOT have a crossout. Idk what that does.
Remove upkeep: does nothing.  The symbol remains not-crossed-out (even without DS installed)

Tested with diamond command baton.

Note 1 =======================================
I noticed that they tend to collide with each other if you command a group to move somewhere.  When entities collide with each other with DS installed, they generally stop what they're doing and look at what they just "bumped into".

If you want to change that, in DS config, go to <server settings -> senses -> touch>
You can add the NPCs to the filter there, or you can disable touch altogether.

If you need to see NPC registry names, go to your modpack folder, then go to config/fantasticlib/reference/entities.txt and search through that file.

Note 2 =======================================
I just noticed that soldiers with upkeep activated (not crossed out) seem to stop obeying orders...probably when they run out of food or something, I assume

---------------------------------------
I think what you ran into is probably one or both of the things I noted above, but if not, just respond to this thread again and I'll reopen this.
