### ISSUE TITLE
Compat w/ Cyclic's Test Dummy

### ISSUE THREAD

**Issue by WenXin20** [Laike-Endaril/Dynamic-Stealth#64]
Minecraft v1.12.2
Forge v14.23.5.2838
Dynamic Stealth v1.12.2.084
[Cyclic](https://www.curseforge.com/minecraft/mc-mods/cyclic) v1.19.12

The Test Dummy can be spawned in using the Target Dummy Spawner wand. It should just be standing still when it's hit, but with this mod it tends to run away...

**Comment by Laike-Endaril** [comment]
This is now fixed in the latest version if you use the new default config setting for entity-specific threat bypass (or if you add "cyclic:robot" to that setting).  Setting is found in:
(server settings -> threat system -> entity specific -> threat bypass)
