### ISSUE TITLE
Shoulder Surfing Reloaded compat

### ISSUE THREAD

**Issue by Phorcis** [Laike-Endaril/Dynamic-Stealth#65]
Sneak indicator always on center in 3rd view

Screenshot - [imgur](https://i.imgur.com/kKEvpsH.png)

**Comment by Laike-Endaril** [comment]
Sorry I never responded; was trying to decide whether I wanted to do compat for this or not

The stealth gauge is not linked to the crosshair; it's just a static position on the screen (configurable, but static) and is in the center of the screen by default

I may look into adding a config for binding it to the crosshair, which should *hopefully* make it compatible with the shoulder surfing mod

**Comment by Laike-Endaril** [comment]
Sorry, but I've decided not to try to bind the stealth gauge to the cursor, due to how I have it set up.

If you're going to be using 3rd person with shoulder surfing, I suggest putting the stealth gauge on the edge of the screen somewhere
