### ISSUE TITLE
Transparent blocks through which entities are not visible

### ISSUE THREAD

**Issue by Phorcis** [Laike-Endaril/Dynamic-Stealth#66]
Iron Bars from **Vanilla**
_Grass Door_ from **Inspirations** works fine
Doors from **Malisis Doors**
Bars, Grass and Frames from **Better Nether**
Bamboo Door from **GrowthCraft**
Windows from **Dark Roleplay Medieval**
Windows, Wooden Bar and Indian Frame from **Millenaire**
Doors from **Natura**

**Comment by Laike-Endaril** [comment]
Huh, I missed iron bars somehow...those will be fixed next update

Modded blocks will be more of a pain to solve in a "correct" way though.  No ETA

Notes to self:
1st filter: t/f blockstate filter config
2nd filter: t/f block filter config
3rd filter: t/f material filter config

**Comment by Laike-Endaril** [comment]
Just uploaded a version of Dynamic Stealth / Fantastic Lib that allow you to customize "see-through" blocks via config.
It's in the Fantastic Lib config, not the DS config (because the library is actually the one doing the raytraces)

Only a year+ later XD
