### ISSUE TITLE
mobs becoming invisible

### ISSUE THREAD

**Issue by ghost** [Laike-Endaril/Dynamic-Stealth#68]
When i don't look at entities directly they seemingly disappear. This happens even if i use vanilla sight or expand the sight angle from the mod configuration options

**Comment by ghost** [comment]
Almost forgot, after some tweaking in the configuration with entity fading options i noticed that only the Lycanite mobs disappear completely. The vanilla ones fade as intended when not seen

**Comment by Laike-Endaril** [comment]
So, with player senses disabled, vanilla mobs still fade, and Lycanite's mobs disappear?

Also, are you connected to a server via the multiplayer menu?

**Comment by ghost** [comment]
I tried using the mod both on my server and in single player, with player senses disabled nothing seem to change

**Comment by Laike-Endaril** [comment]
I've been unable to find anything like this specific to DS <-> Lycanite compat (with the latest versions of each mod ofc)

For player senses, make sure it's disabled on *the server hosting the game*, and that the server is restarted after it is set (I need to re-add the "requires MC restart" tag on that)

Large mobs sometimes have an issue with disappearing when on the edge of sight.  This is a vanilla MC bug

If it's neither of those things, maybe post some screenshots (or better, a video) and I'll take another look
