### ISSUE TITLE
Include RWBY mobs in list of AI that do not check for null

### ISSUE THREAD

**Issue by Jackiecrazy** [Laike-Endaril/Dynamic-Stealth#69]
While digging through the Ice&Fire github I noticed that DS had an issue with I&F due to dragons not checking for null, and you fixed it by adding I&F mobs to some kind of "internal blacklist". Could the same be applied to mobs from RWBY? I'm definitely sure that the juvenile and adult Nevermores have an AI that crashes when using Dynamic Stealth. Not sure about the rest, but their github is at https://github.com/Blaez-Dev/RWBYM-2.0/tree/master/src/main/java/be/bluexin/rwbym/entity

**Comment by Laike-Endaril** [comment]
Yes, I have an internal filter that I can put AI classnames into; I'll take a look

**Comment by Laike-Endaril** [comment]
Crashes should be fixed in latest release (089).

Note that some flying entities tend to lose track of their target with the default settings; may want to look into changing the FOV settings, at least for those mobs (see DS mod description)
