### ISSUE TITLE
Entities always spawn facing south

### ISSUE THREAD

**Issue by genandnic** [Laike-Endaril/Dynamic-Stealth#7]
So this is a quirk of Minecraft itself, but it affects Dynamic Stealth more than anything else. Mobs will always spawn facing south, whether from a spawner or just naturally in the wild. Try running south as fast as you can. You should be able to get the sneak strike on 90% of the mobs you come across. Then turn around and run north for a while and you'll notice an enormous difference. There are also several performance enhancing mods that reduce the radius in which entities are allowed to move that makes this effect more obvious.

![2019-01-02_19 19 03](https://user-images.githubusercontent.com/24349952/50620366-8dfc1e80-0ec4-11e9-9165-aaa88a885c86.png)

**Comment by Laike-Endaril** [comment]
True enough.  I'm not giving an ETA on this right now because I'm in the middle of something already, but I'll look into it eventually.

**Comment by Laike-Endaril** [comment]
This should now be fixed in version 019 and up
