### ISSUE TITLE
Requires version problem with 089

### ISSUE THREAD

**Issue by Phorcis** [Laike-Endaril/Dynamic-Stealth#71]
I cant enter the new world

`Dynamic Stealth: Requires version between 1.12.2.087b and 1.12.2.088a (inclusive) but client has 1.12.2.089.`

**Comment by Laike-Endaril** [comment]
Woops, good catch!  I will patch that very shortly; thanks for the info

**Comment by Laike-Endaril** [comment]
Fixed!  Version 090 is now released with the same features, minus the version mismatch issue
