### ISSUE TITLE
Killing mobs in melee gives brief night vision, soul sight, invisibility, glowing to everything and a console spam error

### ISSUE THREAD

**Issue by Jackiecrazy** [Laike-Endaril/Dynamic-Stealth#72]
As the title says, this fills the console:
https://paste.dimdev.org/arojesizev.mccrash
Occurs when killing any hostile mob in melee. Killing passive mobs will trigger none of the aforementioned effects, and killing mobs via range will also work normally, no matter how close the shot was fired.

**Comment by Jackiecrazy** [comment]
Aha, got it, it's thicc entities. It has an option to change the follow range of entities, but the problem is I kind of need it to give armor points to make certain mobs tougher. Any workarounds?

**Comment by Laike-Endaril** [comment]
The effects themselves are a configurable part of DS (melee assassination; you can't do a melee assassination on passive mobs or with a ranged attack)
server settings -> interactions -> assassination (melee)

The error itself is an attribute being set to a value outside it's allowed range, but the report doesn't give any info on what attribute, what value, etc.  I don't even know for sure if it's linked to the potion effects or not.

That being said, the stacktrace shows that the attribute is being set via a packet, using a scheduled task, on the client side.  At the very least, this means it is not one of my own packets; I don't do anything like that.

I'll go through thicc entities and see if I can find more info and possibly a fix

**Comment by Laike-Endaril** [comment]
Have not seen the error so far with just DS and Thicc Entities installed; default configs on both except I set the wolf toughness to 1, then spawned a bunch, killed some, etc.

If you send me your configs for DS and Thicc, I can run another test.  I'm not sure if the crash is between these two mods or from something else.  Did you test with just DS (and fantastic lib) and Thicc active (all other mods disabled)?

**Comment by Laike-Endaril** [comment]
Wait...if you're running this in a server <-> client setup (LAN or dedicated), you might want to make sure your Thicc config is the same on both the server and all connected clients.

If it's not, then that might potentially cause the error you're showing...

Tell me if that ends up being the cause (or if you find any other info).

If that's not it, then I'm out of ideas between DS <-> Thicc.  It could be from another mod as well; might have to disable/enable mods until you find the one that causes it for sure.  This one is tricky to track down, unfortunately, and I've never seen it happen before

**Comment by Laike-Endaril** [comment]
Sorry for all the messages...

Anyway, did a bit more digging (plus realized you're a developer)
The error is in NetHandlerPlayClient
in the handleEntityProperties() method

Specifically...
```
IAttributeInstance iattributeinstance = abstractattributemap.getAttributeInstanceByName(spacketentityproperties$snapshot.getName());

if (iattributeinstance == null)
{
    iattributeinstance = abstractattributemap.registerAttribute(new RangedAttribute((IAttribute)null, spacketentityproperties$snapshot.getName(), 0.0D, 2.2250738585072014E-308D, Double.MAX_VALUE));
}
```

So it looks like the entity on the client-side does not even *have* whatever attribute is being set, and MC is attempting to add it.

The main issue is probably that the entity doesn't already have the attribute in question.  Unfortunately I still have no idea which attribute that is.

Edit: It could very well be entity ID desync, which might be caused by mismatched mods on the server and client (but could be something else as well)

.

Long story, but basically, I don't have enough info to go on.  If you single out which mods are involved (and with what configs), I can run detailed tests from my end.  Sorry for the book!

**Comment by Jackiecrazy** [comment]
Aha! It's MKUltra. MKUltra adds a reach attribute to every mob, that's probably what's being sent. Don't really know why the problem only pops up with all three mods installed, though.

**Comment by Laike-Endaril** [comment]
Apparently I never submitted my last comment!

Anyway, I still could not produce with basic tests...if you want me to look into it more, send me your configs for all relevant mods and I'll try it again sometime
