### ISSUE TITLE
Dynamic Stealth breaks the Ferrous Wroughtnaut in Mowzies Mobs

### ISSUE THREAD

**Issue by Zunlite** [Laike-Endaril/Dynamic-Stealth#73]
Basically, instead of its normal boss patterns that the boss has, when this mod is installed the boss will glide into the player and spam its attacks, making the fight impossible.

**Comment by Laike-Endaril** [comment]
Yes, I went through looking into the wroughtnaut previously...from a request on the curseforge page for DS (currently on page 3 of the comments).

I have several configs in DS already for general mod compat, but iirc none of them solved this particular mob issue.  I had a *new* system planned that *might* fix the issue, but that system will probably not be done anytime soon.

Leaving this open in case I come back to building said system.

**Comment by Laike-Endaril** [comment]
This should now be fixed in the latest release
