### ISSUE TITLE
Game Crashing while Custom NPCs act hostile

### ISSUE THREAD

**Issue by Eldtrainboy04** [Laike-Endaril/Dynamic-Stealth#74]
The game seems to crash whenever an NPC has a hostile reaction to a target, including the player and other NPCs. I even lost a world because it crashed whenever I loaded it.

The error message in the crash report is
java.lang.NoSuchMethodError: noppes.npcs.api.entity.IPlayer.factionStatus(I)I

Hope this error get's fixed in the future because this mod is so cool and I would love to use it with custom npcs.

Here's the crash log
[crash-2019-09-02_10.15.11-server.txt](https://github.com/Laike-Endaril/Dynamic-Stealth/files/3566604/crash-2019-09-02_10.15.11-server.txt)

**Comment by Laike-Endaril** [comment]
Either the version of CNPCs you're running is either too old, or a more recent version of CNPCs has a breaking change in its API.

Unfortunately, CNPCs doesn't use internal subversioning, so I can only assume you're on an older version...based on the filename...but I could be wrong.  If you can, try using the latest CNPC file available on curseforge (30Jan19).  If that doesn't work, you may need to get on Noppes discord and find the version I *know* works with DS (30May19)

**Comment by Eldtrainboy04** [comment]
It worked! I downloaded the one 30May19 and tested it and it didn’t crash! Thank you so much!

**Comment by Eldtrainboy04** [comment]
It worked! I downloaded the one 30May19 and tested it and it didn’t crash! Thank you so much!
