### ISSUE TITLE
[Crash] with Twilight Forest?

### ISSUE THREAD

**Issue by CactusDuud** [Laike-Endaril/Dynamic-Stealth#76]
Not guaranteed, but Twilight Forest devs seemed confused by this crash and someone said it might be Dynamic Stealth:
https://pastebin.com/5LQnVDY9

**Comment by WenXin20** [comment]
TeamTwilight/twilightforest#817

**Comment by Laike-Endaril** [comment]
I've responded on that thread with details, to keep info in one place.  Feel free to put any responses on that thread as well; I'll get a notification and see them

**Comment by Laike-Endaril** [comment]
Left a bit more info on the other thread.  Closing this one, but I'm still subscribed to the other thread
