### ISSUE TITLE
[Suggestion\compatibility] Special mobs

### ISSUE THREAD

**Issue by shoverno2** [Laike-Endaril/Dynamic-Stealth#77]
There are alots of special mobs in other mods. Their mechanics ruins by this mod. But what about to add in config list of creatures, that ignores this mod, working like there no this mod. Couse your mod AWASOME, and other mobs(even from mods) should have this logic.

**Comment by shoverno2** [comment]
For example, ice and fire. Almost all mobs have specific actions. Whith Dynamic stealth:
Dragons some times don't atack and can't see player.
Ogres will stuck, unnable to die.
Gorgone(when player blind) will make crash...
And others.

**Comment by Laike-Endaril** [comment]
Yes, a full bypass option is on the table...I just haven't had time to do it so far.

I'll leave this open until I can get to it

**Comment by Laike-Endaril** [comment]
The latest release now has an entity-specific full bypass config

Try that out when you get a chance and see if it works for you

**Comment by shoverno2** [comment]
Ok, I will try and reply if there will be some bags.

**Comment by shoverno2** [comment]
Well, it's work.
There list of some mobs that well need to be in list
            dimdoors:mob_monolith
            thaumcraft:cultistportalgreater
            thaumcraft:cultistportallesser
            artifact:mimic
            thaumcraft:taintacle
            thaumcraft:taintaclegaint
            thaumcraft:taintacletiny
            thaumcraft:taintseed
            thaumcraft:taintseedprime
            thaumcraft:taintswarm
            iceandfire:deathworm
            iceandfire:firedragon
            iceandfire:icedragon
            iceandfire:gorgon
            iceandfire:troll
![2019-10-19_19 26 25](https://user-images.githubusercontent.com/50020726/67148323-3e49e080-f2a7-11e9-9330-9f3ceee2eec5.png)
![2019-10-19_18 13 51](https://user-images.githubusercontent.com/50020726/67148325-40ac3a80-f2a7-11e9-9a0b-d8ee1c070a81.png)

**Comment by shoverno2** [comment]
Yeah, i'm from Russia)

**Comment by Laike-Endaril** [comment]
Alright, cool

And thanks for the list!  Going to close this, but I will add them as defaults in the next version (most of those I'm at least somewhat familiar with and they do make sense)
