### ISSUE TITLE
Ancient Warfare 2 NPCs Behavior

### ISSUE THREAD

**Issue by Kiborgs** [Laike-Endaril/Dynamic-Stealth#78]
About problem with orders: NPCs does not obey orders if they in search mode.  As temporary solution this problem can be solved by changing threat degradation rate, but this of course effect all other mobs.

Also some problem with NPCs while DS affect their behavior:
1) NPCs does not move around in search mode but only rotate their heads.
2) Sometimes archers try to move as close as possible, that is very uneffective if they attack walls. Default AW Archers stay on effective range.
3) Then archers does not see path to target they can stuck in flee mode ( if "Flee If Unreachable" ), probably caused by 2 problem.
4) Looks like NPCs very bad at seeing targets who stand above them ( Probable because they dont rotate their heads vertically while in search mode)

**Comment by Laike-Endaril** [comment]
That 4th point is something I eventually need to address for all mobs...

For the rest though, sounds like it's much better to put those NPCs in threat bypass mode so they don't use the DS AI.
(Server settings -> threat system -> entity specific -> threat bypass)

One may think that another solution would be to reset threat to 0 when a new command is issued, but if they can currently see an enemy, they would immediately gain threat again, and go into search mode upon losing sight.

If I wanted to do full compat, I'd probably have to go through every AI task in ancient warfare and decide whether or not it should override the search AI.  That's a lot of work that I don't have time for atm, so see if the threat bypass works out alright for you

**Comment by Laike-Endaril** [comment]
The latest release now has an entity-specific full bypass config.  If threat bypass alone does not work, try adding them to full bypass.  I'm pretty confident it will fix any DS compat issues (by basically not using DS for those mobs)

If you still have problems, tell me and I'll reopen this
