### ISSUE TITLE
Crash with Threat System Bypass

### ISSUE THREAD

**Issue by Secretname2009** [Laike-Endaril/Dynamic-Stealth#8]
[crash-2019-01-04_13.14.46-server.txt](https://github.com/Laike-Endaril/Dynamic-Stealth/files/2726942/crash-2019-01-04_13.14.46-server.txt)
I logged on to the server and changed the difficulty to Easy, i was trying to fix a problem with the mod interfering with a entity from another mod and i hit this crash that was alot different than the last error.
Now i have VanillaFix so it didnt crash me out of the game but it would do that if i didnt.

**Comment by Laike-Endaril** [comment]
Hey there, when you get a chance maybe you could run a test with version 020 and tell me if this is still an issue or not?

**Comment by Secretname2009** [comment]
Im not having this crash anymore so i think that is fixed. I am still however stuck with trying to figure out some other crash that i think your mod is the cause for. Should i just create a New issue for this below or should i just report it to the Developer of the other mod?
[crash-2019-01-04_13.32.43-server.txt](https://github.com/Laike-Endaril/Dynamic-Stealth/files/2728917/crash-2019-01-04_13.32.43-server.txt)

**Comment by Laike-Endaril** [comment]
Hey, sorry for the late reply; I did not get a ping for your last message because the topic had been closed.  I see you've posted an issue report over on the TF2 Stuff issue tracker, so I'll post any news I have over there.
