### ISSUE TITLE
Conflict with Custom NPCs, Optifine

### ISSUE THREAD

**Issue by llazzllo** [Laike-Endaril/Dynamic-Stealth#81]
I recently tried adding Dynamic stealth to my modpack, but it turns my custom npcs inside out when shaders are on. 
![2019-10-30_00 11 26](https://user-images.githubusercontent.com/42483286/67830935-fe5ad880-fab2-11e9-95fc-53020e9a04d6.png)

It also makes them (and mobs from a few other mods) visible through blocks:
![2019-10-30_00 11 51](https://user-images.githubusercontent.com/42483286/67830973-21858800-fab3-11e9-91fd-61676273dd73.png)

**Comment by Laike-Endaril** [comment]
Optifine shaders are incompatible with entity fading and the vanilla glow effect (they use their own glow effect instead, but don't quite detect client glow correctly).  DS uses a glow effect on the currently focused mob by default.

Disable entity fading in (client settings -> entity fading) by setting "min opacity" to 1 and/or "max opacity" to 0...
...and disable the targeting glow in (client settings -> HUD -> targeting HUD style) by setting "glow" to false

Almost 100% sure this should solve the issue, but if not tell me and I'll reopen this

Maybe I'll put a note for this issue in the mod description

**Comment by llazzllo** [comment]
Yes, that fixed it, thank you very much!

**Comment by Laike-Endaril** [comment]
np

**Comment by daniel54bhp** [comment]
> Optifine shaders are incompatible with entity fading and the vanilla glow effect (they use their own glow effect instead, but don't quite detect client glow correctly). DS uses a glow effect on the currently focused mob by default.
> 
> Disable entity fading in (client settings -> entity fading) by setting "min opacity" to 1 and/or "max opacity" to 0... ...and disable the targeting glow in (client settings -> HUD -> targeting HUD style) by setting "glow" to false
> 
> Almost 100% sure this should solve the issue, but if not tell me and I'll reopen this
> 
> Maybe I'll put a note for this issue in the mod description

Can You send screnshot configs pls

**Comment by shdoenjder** [comment]
> > Optifine shaders are incompatible with entity fading and the vanilla glow effect (they use their own glow effect instead, but don't quite detect client glow correctly). DS uses a glow effect on the currently focused mob by default.
> > Disable entity fading in (client settings -> entity fading) by setting "min opacity" to 1 and/or "max opacity" to 0... ...and disable the targeting glow in (client settings -> HUD -> targeting HUD style) by setting "glow" to false
> > Almost 100% sure this should solve the issue, but if not tell me and I'll reopen this
> > Maybe I'll put a note for this issue in the mod description
> 
> Can You send screnshot configs pls

Where are these settings? Searched the entire minecraft and optifine settings and not a single "HUD" or "entity fading" setting exists?
