### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Varg95** [Laike-Endaril/Dynamic-Stealth#83]
ive been having this crash a lot. 

https://pastebin.com/inFC0Xwh
https://pastebin.com/rg3WUXgM
https://pastebin.com/KQXiTALd

I hope this is helpfull and that you can fix it soon.

**Comment by Laike-Endaril** [comment]
These 3 are the same as the 1st, 2nd, and 4th links on #82 (which is not directly related to JED); I'm going to close this one as a duplicate and use #82 as the active thread for this one
