### ISSUE TITLE
[Suggestion] Soul Sight removing config

### ISSUE THREAD

**Issue by Zack7292** [Laike-Endaril/Dynamic-Stealth#85]
you should add a config to disable this soul sight effect to even be activated in your world, bcs won't lie, this is kinda annoying otherwise your mod is pretty cool!

**Comment by Laike-Endaril** [comment]
I assume the activation you're talking about is from assassinations, which is in...
server settings -> interactions -> assassination (melee)

And if you want to disable the potion recipes and items, their configs are in...
server settings -> items -> potions

Just keep in mind that disabling potion items in an already existing world removes forge entries (but forge generally handles this pretty well).  But I'm guessing you probably only care about the assassination trigger anyway

**Comment by Zack7292** [comment]
in 2.0.98, the thing wasn't stopping it from giving me it when deactivated, but now it does!
