### ISSUE TITLE
Turned off glow but still have it

### ISSUE THREAD

**Issue by TheSexyYeti** [Laike-Endaril/Dynamic-Stealth#89]
I've turned off glow and the glow effect still persists. When ever I kill and enemy the screen starts to flash, and every enemy within a certain radius stats flashing. Even through walls. It looked like potion effects. So I even went through the configs and even turned off the potion and potion recipe for soul sight, glow and blindness to get it to go away. But still the same thing. 

![glow](https://user-images.githubusercontent.com/50222286/72668281-3a874080-39f3-11ea-977e-2a99777ce830.png)
![glow2](https://user-images.githubusercontent.com/50222286/72668284-3c510400-39f3-11ea-921e-8ed5e3496352.png)

**Comment by Laike-Endaril** [comment]
By default, DS gives you a buff when you manage a melee assassination.  You can alter this and some similar triggers in...
server settings -> interactions

(The one you're talking about is ofc melee assassination)
