### ISSUE TITLE
Mod not compatible with Shaders Mod

### ISSUE THREAD

**Issue by Cadetri** [Laike-Endaril/Dynamic-Stealth#90]
Hello
I wanted to start by saying that I'm really excited to use this mod. I'm developing an adventure map in the style of Tenchu/Sekiro and I'm stoked to use your stealth system (with CustomNPC's, which i've been told works with this mod, so, MEGA fucking cudos for that). However, I have a few issues and I apologize if they've already been answered.

The first one is that hover targeting does not work with shaders mod. The target space does not surround the entity I point at, and it kinda sticks to the floor off to the right of them.

Similarly, targeted entities (entities I hover my mouse over, not that they actually become targeted) have textures that glitch out, where the side of the entity facing me becomes transparent and all that can be seen is the rear side of the texture.

I have tried with both SEUS-Renewed and Sildurs Vibrant Shaders.

![2020-01-18_20 47 40](https://user-images.githubusercontent.com/60052079/72673129-231c7780-3a34-11ea-8539-dffa87ea4f63.png)
![2020-01-18_20 47 46](https://user-images.githubusercontent.com/60052079/72673130-231c7780-3a34-11ea-89f6-65c02f2da505.png)
![2020-01-18_20 48 41](https://user-images.githubusercontent.com/60052079/72673131-231c7780-3a34-11ea-86fa-1f36c9392722.png)
 
The first two images are with shaders, and the last is without. Thank you very much for any help you can give me :)

Thomas

**Comment by Laike-Endaril** [comment]
For optifine compatibility, do the following:
1. Disable entity fading (client settings -> entity fading) by setting "min opacity" to 1 and/or "max opacity at" to 0
2. Disable targeting glow (client settings -> HUD -> targeting HUD style) by setting "glow" to false

Hopefully that takes care of things.  That being said though, I'm not quite sure what you're referring to in this bit:

"The first one is that hover targeting does not work with shaders mod. The target space does not surround the entity I point at, and it kinda sticks to the floor off to the right of them."

Tell me if those steps fix everything or if some issues remain.

.

I did play the original Tenchu ;)

I haven't played Sekiro yet, though I've looked at it several times...

Here's a few more titles you might be interested in, of various stealth game styles
Mark of the Ninja
Pixel Shinobi
Aragami
Shadow Tactics

Have some others, but those are some of the ones I enjoyed most

**Comment by Cadetri** [comment]
Re:

Thank you very much for your help! I thought I had turned glow off, but apparently not. The blue targeting glow was what I was referring to with the 'targeting space'. Also, the issue of the blue arrows not surrounding the entity when I look at it was fixed when I turned the glow off, so whoopie.

Also, _big dick_ thanks for responding so quickly. I was beyond impressed.

Side note: I was kicking around picking up Aragami, but i'll definitely do it now. You seem like a man of refined taste.

Side Side note: You should really play Sekiro :)

Thanks again
Thomas

**Comment by Laike-Endaril** [comment]
And I actually bought Sekiro last night after responding XD
Good hunting
o7
