### ISSUE TITLE
Server crash while launching (does not occur every times)

### ISSUE THREAD

**Issue by Zack7292** [Laike-Endaril/Dynamic-Stealth#93]
Hey, when i was launching a pack on a server (to experiment the server side) it crash (here's a mediafire link of the pack: https://www.mediafire.com/file/5qoqw0e5ujt009u/infex_serv_.zip/file )
here the crash log: https://pastebin.com/bnfNBDCx

**Comment by Laike-Endaril** [comment]
I've just released a new version of Fantastic Lib ([034](https://www.curseforge.com/minecraft/mc-mods/fantastic-lib/files/2897804)) which should fix this issue.

Try it out when you get a chance and tell me what happens o/

**Comment by Laike-Endaril** [comment]
Closing for now, as this is likely fixed; will reopen if necessary
