### ISSUE TITLE
Hostile worlds invasion mobs or mobs with omniscence from coroutil aren't omniscent

### ISSUE THREAD

**Issue by soupcant95** [Laike-Endaril/Dynamic-Stealth#96]
I'm using coroutil and hostile worlds to make custom invasions where mobs search for the player, knowing where the player is at all times. However, it doesn't work with dynamic stealth. Could you possibly make it so that mobs with coroutil's omniscence cmod work/know where players are all the time?

**Comment by Laike-Endaril** [comment]
Normally I'd say you can do this via the entity-specific soul sight config, but this sounds more like something that needs to happen for mobs *during a certain event*, but not for those same mobs at other times...In which case I don't think it's possible with the current DS version alone. 

I would be fine with adding compat in the source code of DS, but I've been extremely busy elsewhere lately, so I honestly don't know when I'll be active on DS again (other than small patches)

If you feel like attempting a solution right now, DS adds a soulsight potion effect which would be useful, if you could find a way to apply it to the mobs during the event.

I will leave this open as something to look into further on my end when I can

**Comment by Laike-Endaril** [comment]
This ended up being really easy once I figured out what he was doing.  His "omniscience" isn't an AI task or a potion effect...it's just a NBT tag.  Took me a bit to realize that.

This will be implemented in the next release (113)

**Comment by Laike-Endaril** [comment]
This is now available in the latest release (113)
