### ISSUE TITLE
Dynamic light suggestion

### ISSUE THREAD

**Issue by ghost** [Laike-Endaril/Dynamic-Stealth#98]
Add a configurable light level number to player or mob based on items held in either hand

The same way that armor makes you more visible when worn

A torch or any arbitrary item held will add to your visibility

**Comment by Laike-Endaril** [comment]
Related: https://github.com/Laike-Endaril/Dynamic-Stealth/issues/75

I'd like to support moving lights at some point, but when I do, I want to do it correctly (altering server-side block light levels) and efficiently if possible, which will probably be somewhat involved.  This one is on hold for now.

**Comment by Laike-Endaril** [comment]
Going to use the other topic as the main thread for all dynamic light-related conversation (linked above; give it a check for updates)
