### ISSUE TITLE
Bibliocraft Compatibility (or the lack thereof)

### ISSUE THREAD

**Issue by DD12-1916** [Laike-Endaril/Dynamic-Stealth#99]
Low priority, I guess? Anyway, Bibliocraft Armour Stands render incorrectly, as either Steve or Alex's player models appear when the armour stands are placed down. In contrast, vanilla armour stands appear to be normal.

I have confirmed that Dynamic Stealth is indeed the cause, mainly because I saw a person in a Discord server mention that this was the case. I have also tried to put in the Bibliocraft Armour Stands in the Entity-Specific Full Bypass to see if that would work, but sadly, it didn't. I put in 'bibliocraft:armorstand', which was the ID of the item. Turns out, no such entity exists for any of the armour stands, as far as I know.

![Screenshot (22)](https://user-images.githubusercontent.com/65891914/82796432-20310800-9ea8-11ea-939b-dfb23a82b83b.png)

By the way, such an awesome mod you got here :)

**Comment by Tommsy64** [comment]
It looks like the Bibliocraft armor stand renderer uses the following AbstractClientPlayer class
```java
public class AbtractSteve extends AbstractClientPlayer {
    private static GameProfile gp = new GameProfile(UUID.randomUUID(), "BiblioSteve");

    public AbtractSteve(World world) {
        super(world, gp);
        this.setInvisible(true);
    }
}
```
while Dynamic Stealth sets every entity to be visible before rendering.
```java
    @SubscribeEvent(priority = EventPriority.LOWEST, receiveCanceled = true)
    public static void preRender(RenderLivingEvent.Pre event) {
    ......
        //Don't draw seen entities as invisible, because they've been SEEN
        livingBase.setInvisible(false);
```

**Comment by Laike-Endaril** [comment]
Sorry I've been inactive on here for a while; looking through this one now (and I do see your related PR)

**Comment by Laike-Endaril** [comment]
This should now be fixed in the latest release (104)

**Comment by DD12-1916** [comment]
I tested 1.0.4 just now and it does indeed work, thank you so much!

**Comment by Laike-Endaril** [comment]
Thanks again @Tommsy64 for this one, you're in the mod credits
